### ISSUE TITLE
Problem with opening certain HDRP shader source files

### ISSUE THREAD

**Issue by tzaeru** [game-ci/unity-builder#131]
So this is really probably not related to Unity Builder, but since this doesn't happen on my nor teammates' computers, I figured I'd anyway open an issue here in case it was related to Unity Builder or if in future someone else has the same problem, then they can maybe find a solution here.

When building, I get a bunch of compiler errors like so:
`Shader error in 'RaytracingShadow.compute': failed to open source file: 'Packages/com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/HDRayTracingManager.cs.hlsl' at kernel OutputShadowTexture at Packages/com.unity.render-pipelines.high-definition/Runtime/RenderPipeline/Raytracing/Shaders/ShaderVariablesRaytracing.hlsl(1) (on d3d11)`

Not really sure what causes that, since I can build fine on my own computer. Maybe outdated packages? Some package not being installed in a similar way on the Ubuntu image as on Windows?

**Comment by tzaeru** [comment]
I reset the packages to default (as RaytracingShadow.compute comes from the High Definition Rendering Pipeline package) and installed the High Definition Rendering Pipeline again. The problem is still there.

So at least in my case in this repo on my Unity version (2019.3.6.1f) the problem can be removed and reproduced by removing and reinstalling the HD Rendering Pipeline package.

**Comment by webbertakken** [comment]
This looks like a faulty dependency that has probably been updated to work again by now. Assuming this is no longer an issue.
