### ISSUE TITLE
Add IL2CPP support for Android, iOS, Linux

### ISSUE THREAD

**Issue by RDeluxe** [game-ci/unity-builder#143]
**Context**

Seems that linux docker images with IL2CPP are ready => https://gitlab.com/gableroux/unity3d/-/issues/66
It would be nice to be able to use them.

**Suggested solution**

Considering IL2CPP + Windows target is not possible ATM, an action parameter could be tricky. However I don't see any better solution.

**Comment by webbertakken** [comment]
Hi @RDeluxe thank you for your input.

I agree with the suggested solution. Accepting PRs for the suggested changes.

Please note though that is currently blocked by https://gitlab.com/gableroux/unity3d/-/issues/85.

**Comment by RDeluxe** [comment]
Hi !

Yes I'm currently using a fork to use a working Android image. I'm not quite sure how things are going to evolve without changing the images name though. I'll keep an eye on that.

I realized that https://gitlab.com/gableroux/unity3d/-/issues/66 did not include IL2CPP images for iOS nor Android, but only for linux.

That means a first MR would be required to add `android-il2cpp` and `ios-il2cpp` before creating a PR here. Am I right ?

**Comment by webbertakken** [comment]
Yes, as we are using [gableroux/unity3d](https://gitlab.com/gableroux/unity3d/) images, so we would need to see the [images (#il2cpp)](https://hub.docker.com/r/gableroux/unity3d/tags?page=1&name=il2cpp) in dockerhub before we can use  them.

**Comment by davidmfinol** [comment]
I think the Android and iOS images include il2cpp by default. I've been using il2cpp for Android and iOS builds through unity 
 actions without problem.

I would really like to see il2cpp for linux added, though.

**Comment by RDeluxe** [comment]
That's weird, the previous issue mentioned a new naming scheme for il2cpp images, because of the added "weight". Maybe @GabLeRoux can confirm ? It's not clear digging in the sources.

I'll test that as soon as I can find a working Android image 😅

**Comment by GabLeRoux** [comment]
I don't know if latest images have `IL2CPP` support by default for ios and android, I'd have to confirm this too. Here's a summary of what I know and from where:

**Linux** `IL2CPP` support in docker images was added here:
* issue: https://gitlab.com/gableroux/unity3d/-/issues/66
* merge request: https://gitlab.com/gableroux/unity3d/-/merge_requests/99

**Windows** `IL2CPP` support was requested here:  
* issue: https://gitlab.com/gableroux/unity3d/-/issues/36

But as described in the discussion, last time I checked (4 months ago), Unity doesn't have support for installing `IL2CPP` windows component when unity is running on Linux (and docker images are based on Ubuntu so we can only do what unity on Ubuntu can do).

**Android** `IL2CPP` was discussed in the following comment:
* https://gitlab.com/gableroux/unity3d/-/issues/66#note_313808638
> From the screenshot, android-il2cpp doesn't seem to be available (yet)

A quick way to confirm this would be to run Ubuntu locally, install unity with android build support and see if it's possible to build a project with IL2CPP and `arm64` checked [as shown how to here](https://forum.unity.com/threads/fixed-il2cpp-for-linux-64-bit-android.685198/#post-4585897).

> I'll test that as soon as I can find a working Android image 😅
This is definitely related to https://gitlab.com/gableroux/unity3d/-/issues/85

**Comment by davidmfinol** [comment]
I don't think there's much discussion to be had about iOS. [Unity requires IL2CPP for 64-bit iOS builds](https://docs.unity3d.com/2018.2/Documentation/Manual/iphone-64bit.html),  [Apple now requires 64-bit for new iOS apps](https://developer.apple.com/documentation/uikit/app_and_environment/updating_your_app_from_32-bit_to_64-bit_architecture), so [IL2CPP is now the only option for building to iOS](https://docs.unity3d.com/Manual/PlayerSettingsiOS-Other.html#Config-API).

**Comment by webbertakken** [comment]
Could anyone confirm that this works?

**Comment by davidmfinol** [comment]
I tried using [unity-builder@v2.0-alpha-2](https://github.com/finol-digital/Card-Game-Simulator/actions/runs/362368050/workflow#L38), but my [Linux Il2CPP build fails](https://github.com/finol-digital/Card-Game-Simulator/runs/1398028222?check_suite_focus=true#step:5:2830) (Android and iOS are good, though!).

Maybe there is some additional step required to get IL2CPP working on Linux?

**Comment by webbertakken** [comment]
I think this will fix it https://github.com/webbertakken/unity-builder/pull/177

**Comment by davidmfinol** [comment]
Looks like its still [using the base image instead of IL2CPP](https://github.com/finol-digital/Card-Game-Simulator/runs/1416025024?check_suite_focus=true#step:5:106):
```
/usr/bin/docker build /home/runner/work/_actions/webbertakken/unity-builder/v2.0-alpha-4/action --file /home/runner/work/_actions/webbertakken/unity-builder/v2.0-alpha-4/action/Dockerfile --build-arg IMAGE=unityci/editor:2019.4.9f1-base-0 --tag unity-builder:2019.4.9f1-base-0
```

I can run a snippet similar to the logic we've got:
```
function imageSuffixes() {
    return {
      generic: '',
      webgl: 'webgl',
      mac: 'mac-mono',
      windows: 'windows-mono',
      linux: 'base',
      linuxIl2cpp: 'linux-il2cpp',
      android: 'android',
      ios: 'ios',
      facebook: 'facebook',
    };
}
const {
      generic,
      webgl,
      mac,
      windows,
      linux,
      linuxIl2cpp,
      android,
      ios,
      facebook,
    } = imageSuffixes();
const version = '2019.4.9f1';
const [major, minor] = version.split('.').map((digit) => Number(digit));
if(major >= 2020 || (major === 2019 && minor >= 3)) 
  console.log(linuxIl2cpp);
else
  console.log(linux);
```

Running this snippet returns "linux-il2cpp" instead of "base", so I'm not sure what's wrong now. 
I might try looking into it some more tomorrow.

**Comment by davidmfinol** [comment]
I forgot to run `yarn build` for index.js with the last PR. I think it should be fixed with https://github.com/webbertakken/unity-builder/pull/181

**Comment by davidmfinol** [comment]
Ok, it's using the correct image now, but now I'm getting [this error](https://github.com/finol-digital/Card-Game-Simulator/runs/1427215313?check_suite_focus=true#step:5:4161):
`Error:  FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: C++ code builder is unable to build C++ code for Linux: Could not find valid clang executable at clang`

@GabLeRoux started looking into this at https://gitlab.com/gableroux/unity3d-gitlab-ci-example/-/issues/139

**Comment by webbertakken** [comment]
That's good news. So we're 1 step closer again 👍🏼

**Comment by davidmfinol** [comment]
Linking to https://github.com/Unity-CI/docker/issues/53 for visibility.

**Comment by webbertakken** [comment]
Images have been reported to work with Android and iOS as build targets. Their default backend is set to IL2CPP, at least for newer versions of Unity editor.

Closing this unless there is indeed reason to believe we need to further investigate any missing dependencies.
