### ISSUE TITLE
Use ProjectSettings/ProjectVersion.txt

### ISSUE THREAD

**Issue by dantman** [game-ci/unity-builder#162]
**Context**

When using Unity Hub it manages the Unity version in `ProjectSettings/ProjectVersion.txt` and automatically updates it when you change the version in Unity Hub.

I think it would be good to support this as an alternative to explicitly declaring the version in `with.unityVersion` on the builder action.

**Suggested solution**

This should probably be opt-in. `unityVersion` could accept a special value indicating to read `{projectPath }/ProjectSettings/ProjectVersion.txt` for the Unity version in `m_EditorVersion`.

**Comment by davidmfinol** [comment]
I think this is a great idea. 
I think we may even want to take it a step further: If someone does not set `unityVersion`, then we could default it to this value?

What would this value be? Would it make sense to have it be a number like 0 or -1?

**Comment by webbertakken** [comment]
I was thinking the same thing. Perhaps just "auto" and set it as default when not defined.

**Comment by webbertakken** [comment]
Note that that will only work with the newer images though. As the current ones have a different hardware ID for every version of unity.

**Comment by GabLeRoux** [comment]
Indeed, upgrading the version manually will directly lead to a _wrong license_ error, but we'll fix that shortly when the new images are published and widely used. I'd go exactly as Webber said too: https://github.com/webbertakken/unity-builder/issues/162#issuecomment-712392231

**Comment by webbertakken** [comment]
This is now possible in v2 alpha
