### ISSUE TITLE
Build fails with 'Error: Failed to parse git describe output: "v0.1.0a-26-g6817b33'

### ISSUE THREAD

**Issue by GabLeRoux** [game-ci/unity-builder#163]
**Bug description**

When using a tag that does not 100% respect a classic _semver_ version, `unity-builder` fails with the following error message:

```
Error: Failed to parse git describe output: "v0.1.0a-26-g6817b33
```

**How to reproduce**

1. Use unity-actions@v1.4
2. push a commit and a tag like `v0.1.0a` to trigger the pipeline

It should build, but it fails.

**Comment by GabLeRoux** [comment]
Problems relates to the following section in the code:
https://github.com/webbertakken/unity-builder/blob/v1.4/src/model/versioning.js#L71

the error that is thrown comes from the following try catch:
https://github.com/webbertakken/unity-builder/blob/v1.4/src/model/versioning.js#L150-L165

We may have to update the regex or even allow any bad tag that cannot be properly identified.

**Comment by webbertakken** [comment]
Actually `0.1.0a` is not a valid version according to the [semver](https://semver.org/) specification.

If anything we should account for `1.x.x-alpha-x`. Anything below 1.0 should already not be considered as stable.

At some point we need to use `semver` package to do the parsing. Moving away from that is not a good idea in my opinion.

**Comment by GabLeRoux** [comment]
let's not loose sight on actual bug: the build fails when we use non semver tags and it should not fail, it should only throw a warning.

**Comment by caiusno1** [comment]
Is that right https://github.com/webbertakken/unity-builder/pull/171#issuecomment-720619144? @GabLeRoux and @webbertakken ?

**Comment by caiusno1** [comment]
And btw. Should we allow only semVer or should that be semVers-commits-hash ? I am a bit confused tbh xd.

**Comment by GabLeRoux** [comment]
> And btw. Should we allow only semVer or should that be semVers-commits-hash ? I am a bit confused tbh xd.

answered here: https://github.com/webbertakken/unity-builder/pull/171#issuecomment-720655173

**Comment by GabLeRoux** [comment]
I think I also reproduced this problem with tags that looked like this in the repository:

```
0.0.1 # this one not starting with v seems to have caused the same error message
v0.0.2
v0.1.0
```

**Comment by hsravat-4590** [comment]
I'm still getting this error on my project:
```
2.1.0-0-g63d8fd1

Warning: describe 63d8fd121525a20dec00d66b4f3c2681986e7cf6

Error: Failed to parse git describe output: "2.1.0-0-g63d8fd1
```

Please advise on the best couse of action

**Comment by webbertakken** [comment]
Creating a tag on your main branch `v2.1` should fix your problem as per https://github.com/game-ci/unity-builder/issues/163#issuecomment-723582126.

**Comment by Laurens54321** [comment]
I'm also still getting this error 

```
v0.0.2-release.0-0-gd2d2302

Warning: describe d2d230285bca702c1a7e3ccda9e0c3d021d3a92b

Error: Failed to parse git describe output: "v0.0.2-release.0-0-gd2d2302
".
```

**Comment by webbertakken** [comment]
> I'm also still getting this error
> 
> ```
> v0.0.2-release.0-0-gd2d2302
> ```

Please see https://game.ci/docs/github/builder#versioning for the available versioning options.

**Comment by montao** [comment]
Happened to me `"Failed to parse git describe output: "v0.1.1a-0-g8de361f"`

**Comment by davidmfinol** [comment]
The fix for this was merged to main a while ago.
@webbertakken We should probably release a new version of Unity Builder?
@montao You could try temporarily using `uses: game-ci/unity-builder@main` if you don't want to wait.
