### ISSUE TITLE
Auto build addressables.

### ISSUE THREAD

**Issue by gpiffaretti** [game-ci/unity-builder#176]
**Context**

Addressables is an asset solution with increasing popularity. Building these assets used to be automatically but Unity has disabled this because it didn't scale well in bigger projects. At the moment the only way to auto build these assets is with a custom build script.

**Suggested solution**

Update the build script method so that it includes the `AddressableAssetSettings.BuildPlayerContent();` call. Maybe some configuration is needed, not sure at the time. A new input for the action would be nice to let us choose if we want to build addressables or not.

**Comment by hookkshot** [comment]
This is a few months old now. Is anything happening with it.

**Comment by webbertakken** [comment]
It's a great idea. We're open for contributions.

**Comment by hookkshot** [comment]
I have made a Fork and did it on 1.5 as we couldnt get the 2.0 alpha working. 

The problem I see for putting this in for everyone is not everyone will have the Addressables package installed. So it will fail for all those that don't. I am assuming there is no way to do #IF PACKAGE type of command?

**Comment by webbertakken** [comment]
Version 1 will soon be discontinued so that will not be very helpful honestly.

There may not be a pragma for `#IF PACKAGE` but that would also be semantically incorrect.
Instead we can simply parse the packages manifest and check if the `Addressables` package is present.

This can be done as part of the javascript or as part of the c# build script.

**Comment by hookkshot** [comment]
Got any pointers for doing it as part of the c# build script.

**Comment by webbertakken** [comment]
You can adapt the default build script (part of this repo) to have it read the packages file and check if it contains a definition for Addressables, and if so; build with addressables support.

**Comment by webbertakken** [comment]
There's also an implementation from javascript side that's already [implemented](https://github.com/game-ci/unity-test-runner/pull/84/files) in test runner.

**Comment by davidmfinol** [comment]
This issue should be resolved by https://github.com/game-ci/unity-builder/pull/231, right?

**Comment by webbertakken** [comment]
Yes, I assume it should close this issue. If not, please report a bug or reopen.
