### ISSUE TITLE
WebGL builds throw error in v2.0-alpha-3 (probably due to missing Python)

### ISSUE THREAD

**Issue by mgrman** [game-ci/unity-builder#179]
**Bug description**
WebGL build in v2.0-alpha-3 throws error. WebGL build works fine in v1.4

**How to reproduce**
See build run https://github.com/mgrman/Votyra/runs/1400468521

**Expected behavior**
Build working as in run https://github.com/mgrman/Votyra/runs/1395981211

**Additional details**
Exception highlighted during build: 

```
Error:  FATAL UNHANDLED EXCEPTION: System.AggregateException: One or more errors occurred. ---> System.ComponentModel.Win32Exception: ApplicationName='/usr/bin/python', CommandLine='-E "/opt/unity/Editor/Data/PlaybackEngines/WebGLSupport/BuildTools/Emscripten/emcc" -Wno-unused-value -Wno-invalid-offsetof -nostdinc -fno-strict-overflow -Wno-null-conversion -O3 -Oz -DNET_4_0 -DUNITY_AOT -DIL2CPP_MONO_DEBUGGER_DISABLED -DGC_NOT_DLL -DRUNTIME_IL2CPP -DNDEBUG -I"/opt/unity/Editor/Data/il2cpp/libil2cpp" -I"/opt/unity/Editor/Data/il2cpp/libil2cpp" -I"/opt/unity/Editor/Data/il2cpp/external/bdwgc/include" -I"/opt/unity/Editor/Data/il2cpp/external/xxHash" -I"/github/workspace/Temp/StagingArea/Data/il2cppOutput" "/github/workspace/Temp/StagingArea/Data/il2cppOutput/Il2CppMetadataUsage.c" -o "/github/workspace/Library/il2cpp_cache/A3C7AA774E6E8068B2B5CD91EE061319.o"', CurrentDirectory='', Native error= Cannot find the specified file
```

Seems like Python is missing?

**Comment by davidmfinol** [comment]
Is this related to the issue that @GabLeRoux has at https://gitlab.com/gableroux/unity3d-gitlab-ci-example/-/issues/139 ?

**Comment by louis030195** [comment]
Same here on v2.0-aplha-5 https://github.com/louis030195/niwrad/runs/1539500329?check_suite_focus=true#step:4:1495. :cry:

**Comment by webbertakken** [comment]
We have clues to a solution here: https://github.com/game-ci/docker/issues/53.

Leaving this issue open for the time being, but please feel free to pitch in to that issue if you want to help us move this forward.

**Comment by davidmfinol** [comment]
Python has been added in v0.9 of the unity-editor images.
