### ISSUE TITLE
Unity Floating Licensing 

### ISSUE THREAD

**Issue by benoitdion** [game-ci/unity-builder#185]
I'm investigating using the Unity Floating License model to help increase parallelization of Unity builds. Have you investigated how it could be integrated with unity-builder? 

I'd be happy to contribute that feature but wanted to brainstorm how it could work first. Attaching the relevant unity docs for reference: [UnityFloatingLicenseSetupGuide.pdf](https://github.com/game-ci/unity-builder/files/5668131/UnityFloatingLicenseSetupGuide.pdf)

**Comment by webbertakken** [comment]
Thank you for this idea @benoitdion,

I have read the about part, and did not find anything about the problem that it solves. Could you shed some light on this? 

For example, currently unity builder takes a license, runs the build and returns the license (using Unity's licensing server), which works in parallel if you have enough licenses.  How would floating licenses improve the status quo?

**Comment by benoitdion** [comment]
Unity offers a cheaper licensing scheme ($600 per license) for server builds. The way it seems to be working is you need to host your own licensing server and a client library can be used to acquire a floating license when starting a build.

**Comment by webbertakken** [comment]
Thanks for the additional context. Sounds good to me.

**Comment by gabor-simon-greentube** [comment]
Hello! Any news on this one? I would be interested in using it in our project.

**Comment by webbertakken** [comment]
As far as I know multiple people teams have started using floating licenses, it might not need changes from unity-builder side.

**Comment by webbertakken** [comment]
Closing for the lack of further details by the community.
