### ISSUE TITLE
License activation strategy could not be determined.

### ISSUE THREAD

**Issue by superbderrick** [game-ci/unity-builder#187]
Hi there, 

I just tried to build my demo project with GIthub Action but it Could not build well

In order to build with GIthub action, I did like steps with document guid lines 

1. I did set up some select values on GIthub Serect tap 
- UNITY_SERIAL
- UNITY_PASSWORD
- UNITY_EMAIL

2.I wrote the yml file like this.

    name: Actions 😎
    
      
    
    on:
    
    pull_request: {}
    
    push: { branches: [main] }
    
      
    
    env:
    
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    
      
    
    jobs:
    
    readmeWorkflow:
    
    name: Readme Workflow ✨
    
    runs-on: ubuntu-latest
    
    steps:
    
    # Checkout
    
    - name: Checkout repository
    
    uses: actions/checkout@v2
    
      
    
    # Build
    
    - name: Build project
    
    uses: webbertakken/unity-builder@v0.10
    
    with:
    
    projectPath: UnityActionTest
    
    unityVersion: 2019.4.0f1
    
    targetPlatform: Android
    
      
    
    # Output
    
    - uses: actions/upload-artifact@v1
    
    with:
    
    name: Build
    
    path: build

If the build fails, it comes out like this at the end,

Is there anything I am missing?

    `Removing intermediate container e6e0f6630c87
    
    ---> adefeb296928
    
    Successfully built adefeb296928
    
    Successfully tagged unity-builder:2019.4.0f1-android
    
    /usr/bin/docker run --workdir /github/workspace --rm --env UNITY_LICENSE --env UNITY_EMAIL --env UNITY_PASSWORD --env UNITY_SERIAL --env UNITY_VERSION=2019.4.0f1 --env PROJECT_PATH=UnityActionTest --env BUILD_TARGET=Android --env BUILD_NAME=Android --env BUILD_PATH=build/Android --env BUILD_FILE=Android.apk --env BUILD_METHOD= --env CUSTOM_PARAMETERS= --env HOME=/github/home --env GITHUB_REF --env GITHUB_SHA --env GITHUB_REPOSITORY --env GITHUB_ACTOR --env GITHUB_WORKFLOW --env GITHUB_HEAD_REF --env GITHUB_BASE_REF --env GITHUB_EVENT_NAME --env GITHUB_WORKSPACE=/github/workspace --env GITHUB_ACTION --env GITHUB_EVENT_PATH --env RUNNER_OS --env RUNNER_TOOL_CACHE --env RUNNER_TEMP --env RUNNER_WORKSPACE --volume /var/run/docker.sock:/var/run/docker.sock --volume /home/runner/work/_temp/_github_home:/github/home --volume /home/runner/work/_temp/_github_workflow:/github/workflow --volume /home/runner/work/UnityActionTest/UnityActionTest:/github/workspace unity-builder:2019.4.0f1-android
    
    License activation strategy could not be determined.
    
      
    
    Visit https://github.com/webbertakken/unity-builder#usage for more
    
    details on how to set up one of the possible activation strategies.
    
    Error: The process '/usr/bin/docker' failed with exit code 1
    
    0s
    
    `

**Comment by superbderrick** [comment]
My project configuration is attached the image
![Screen Shot 2020-12-14 at 2 39 44 PM](https://user-images.githubusercontent.com/7856611/102045953-96ce2c80-3e1d-11eb-88fb-c303703197f6.png)

**Comment by webbertakken** [comment]
Yes, you have to pass the environment variables to the builder. See the [builder docs](https://game.ci/docs/github/builder).

**Comment by superbderrick** [comment]
Thanks kindly reply @webbertakken , It was working well iOS Platforms after added more environment variables  

But Android is still not working well 


Can you check it out?
In my project, I set android sdk min and target appropriately.

`
Detected outdated SDK Tools version 0.0 when the min version is 26.1.1
Detected outdated SDK Tools version 0.0 when the min version is 26.1.1
 File /root/.android/repositories.cfg could not be loaded.
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
UnityEditor.Android.AndroidSDKTools:DetectErrorsAndWarnings(String, String)
UnityEditor.Android.AndroidSDKTools:RunAndroidSdkTool(String, String, Boolean, String, String)
UnityEditor.Android.AndroidSDKTools:RunAndroidSdkTool(String, String, Boolean, String)
UnityEditor.Android.AndroidSDKTools:UpdateSDK()
UnityEditor.Android.PostProcessor.Tasks.SDKComponentDetector:Update(AndroidSDKTools, Version, ProgressHandler)
UnityEditor.Android.PostProcessor.Tasks.CheckAndroidSDK:EnsureSDKComponentVersion(Version, SDKComponentDetector)
UnityEditor.Android.PostProcessor.Tasks.CheckAndroidSDK:Execute(PostProcessorContext)
UnityEditor.Android.PostProcessor.PostProcessRunner:RunAllTasks(PostProcessorContext)
UnityEditor.Android.PostProcessAndroidPlayer:PrepareForBuild(BuildOptions, BuildTarget)
UnityEditor.Android.AndroidBuildPostprocessor:PrepareForBuild(BuildOptions, BuildTarget)
UnityEditor.PostprocessBuildPlayer:PrepareForBuild(BuildOptions, BuildTargetGroup, BuildTarget) (at /home/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:149)
UnityEditor.BuildPipeline:BuildPlayerInternalNoCheck(String[], String, String, BuildTargetGroup, BuildTarget, BuildOptions, Boolean)
UnityEditor.BuildPipeline:BuildPlayerInternal(String[], String, String, BuildTargetGroup, BuildTarget, BuildOptions) (at /home/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline.bindings.cs:376)
UnityEditor.BuildPipeline:BuildPlayer(String[], String, String, BuildTargetGroup, BuildTarget, BuildOptions) (at /home/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline.bindings.cs:275)
UnityEditor.BuildPipeline:BuildPlayer(BuildPlayerOptions) (at /home/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline.bindings.cs:258)
UnityBuilderAction.Builder:BuildProject() (at Assets/Editor/Editor/Builder.cs:97)`

**Comment by webbertakken** [comment]
This is because you're running an outdated version of builder. The old images don't support Android builds any longer (which was the reason to create and move to the new images)

**Comment by superbderrick** [comment]
Thanks kindly reply, Happy Christmas
