### ISSUE TITLE
Auto renew license

### ISSUE THREAD

**Issue by jcs090218** [game-ci/unity-builder#193]
**Context**

Automatically renew the license so user does not have to renew it itself.

**Suggested solution**

Not really, I guess I am open for suggestion and looking for best solution.

**Comment by webbertakken** [comment]
Could you elaborate on what you mean by renewing the license and perhaps paint it with your practical use case, so it becomes a bit more clear what is meant by this issue?

**Comment by jcs090218** [comment]
This may be a question instead of an issue. I was wondering if there is a way that CI could automatically update/renew the free license once it is expires?

**Comment by webbertakken** [comment]
It depends a lot on your use case I would say, as Unity has a big ecosystem.

For personal licenses you have to use an activation file (.alf) to manually acquire a license file (.ulf) from the website and that file has not been reported to ever expire. The manual process however can be automated; see that we have [permission](https://github.com/kuler90/activate-unity/issues/1) to use another project. Contributions are welcome.

For professional licenses this process goes automatically when providing username, password and serial number. Builder activates your license (1 slot), and returns it after. This license has not been reported to expire during a build either.

For other types of licenses (corporate, licensing servers, some other custom types perhaps) we do not have enough information.

Does this answer your question?

**Comment by jcs090218** [comment]
> For personal licenses you have to use an activation file (.alf) to manually acquire a license file (.ulf) from the website and that file has not been reported to ever expire. The manual process however can be automated; see that we have permission to use another project. Contributions are welcome.

Ah, I am using personal license (free). I do acquired the `.ulf` file from the website then the CI works. But after few days the CI stops working. Here is the log https://github.com/jcs090218/JCSUnity/runs/1905483230. What could go wrong by this scenario? 😕

**Comment by webbertakken** [comment]
> > For personal licenses you have to use an activation file (.alf) to manually acquire a license file (.ulf) from the website and that file has not been reported to ever expire. The manual process however can be automated; see that we have permission to use another project. Contributions are welcome.
> 
> Ah, I am using personal license (free). I do acquired the `.ulf` file from the website then the CI works. But after few days the CI stops working. Here is the log https://github.com/jcs090218/JCSUnity/runs/1905483230. What could go wrong by this scenario? 😕

This is likely due to Unity servers having some hiccups. Could you give it a few tries and see if it start working again? 🔮

**Comment by webbertakken** [comment]
As the opening post seems to no longer be needed, I'll close this issue.

Please feel free to create a new issue if there is indeed something broken.
