### ISSUE TITLE
Requesting activation (personal license)

### ISSUE THREAD

**Issue by matrix3d** [game-ci/unity-builder#199]
Requesting activation (personal license)
Unclassified error occured while trying to activate license.

I can't use it suddenly today, do I need to reapply?

**Comment by webbertakken** [comment]
@matrix3d did you change anything at all?

Note that if you move to v2, that you'll need to reactivate (using v2 of the activation action),

**Comment by matrix3d** [comment]
I re-applied for the certificate and it’s okay now
