### ISSUE TITLE
Add preprocessor define symbols to Unity builder

### ISSUE THREAD

**Issue by xibz** [game-ci/unity-builder#207]
**Context**

Basically, we have a few preprocessor macros that we use and it looks like there isn't an easy way of doing that without creating a custom builder. However, I think being able to specify custom defined symbols via `yaml` would be really nice!

So I was thinking something like this
```yaml
defines:
    - STEAM
```

I can implement this, if this is something you'd think would be worth having.

**Comment by webbertakken** [comment]
Could you perhaps further describe your use case and help me better understand whether this is something others might be able to use too, or it being too specific for our project. Personally I've never used them.

I also didn't know github actions supports `defines` as a key.

**Comment by xibz** [comment]
What we do is we use preprocessor definitions to dictate code for Steam, Epic Games, and other things like that. So, It'd be nice to be able to have integration test that target those set those definitions. I hope that makes sense

**Comment by webbertakken** [comment]
Personally I have but a year of hobby experience with Unity so I'm having trouble fully understanding what "dictate code for Steam, Epic Games, and other things like that" means exactly. And how it works from a functional perspective. I really do not know your use case or anything like it. You're also the first one bringing it up, so it'd be great if you could elaborate on how your use case works exactly.

Could you also speak for whether you can use `customParameters` for that and whether a custom `buildMethod` worked or could work for your use case?

**Comment by webbertakken** [comment]
This has been discussed on discord.

The used solution was to have

```csharp
PlayerSettings.SetScriptingDefineSymbolsForGroup(BuildTargetGroup.Standalone, "SYMBOL_HERE");
```

Note that it's set symbol**s**, so it overrides all of them. So you'll want to use it in conjunction with `GetScriptingDefineSymbolsForGroup`.

**Comment by pearcemichal** [comment]
in the past, I used the scripting defines to create separate release and demo builds for my game. based on the description of the customParameters, I thought something like `customParameters: -DEMO` would work, but based on my testing it does not. 

I do not understand what the stated solution to this is. could you please describe the process in more detail? (or add it to the documentation somewhere, for future reference)

**Comment by pearcemichal** [comment]
I got it working, I will post the process here for anyone else that comes across this: 

first, I set up my project to use a custom build script by following the steps in the documentation here: 
[https://game.ci/docs/github/builder](https://game.ci/docs/github/builder)

relevant sections are buildMethod and customParameters

after copying the supplied template buldMethod.cs file into the `Assets/Editor/UnityBuilderAction` folder, in the `GetValidatedOptions()` method, I added the following if statement: 
```
if (validatedOptions.TryGetValue("DEMO", out string _))
{
    string definesString = PlayerSettings.GetScriptingDefineSymbolsForGroup ( EditorUserBuildSettings.selectedBuildTargetGroup );
    definesString += ";DEMO";
    PlayerSettings.SetScriptingDefineSymbolsForGroup(EditorUserBuildSettings.selectedBuildTargetGroup, definesString);
}
```

this will look for a customParameters -DEMO, and if it finds it, it will add it to the scripting defines list. 

the yml code: 
```
with:
    targetPlatform: StandaloneWindows64
    buildName: debris_field_demo_PC
    buildsPath: demo
    versioning: Semantic
    buildMethod: UnityBuilderAction.BuildScript.Build
    customParameters: -DEMO
```

**Comment by xwipeoutx** [comment]
🧟

For anyone coming across this later, I took a different approach - generate a `csc.rsp` file that includes the pre-processor symbols.

```yaml
steps:
  - name: Apply csc.rsp (pre-processor symbols)
    run: echo -define:MY_SYMBOL >> Assets/csc.rsp
```

You will get warnings about "unapplied changes" - you could get around this by putting `csc.rsp` in your `.gitignore`, or allowing dirty build.

```yaml
with:
  # ...
  allowDirtyBuild: true
```

Now in your code you can just do this:
```c
void Start() {
#if MY_SYMBOL
  GetComponent<TMP_Text>().text = "I have a symbol!";
#else
  GetComponent<TMP_Text>().text = "I do not have a symbol...";
#endif
}
```

**Comment by efarraro** [comment]
I updated to use the solution from xwipeoutx and can confirm it works - nice catch! Very clean & easy solution. Feels like something that needs to be added to the official documentation.
