### ISSUE TITLE
can i build ipa use the lib？github action

### ISSUE THREAD

**Issue by matrix3d** [game-ci/unity-builder#210]

**Comment by davidmfinol** [comment]
This question isn't really well-formed, but I'm guessing it's a duplicate of this?: https://github.com/game-ci/unity-builder/issues/212

**Comment by matrix3d** [comment]
> This question isn't really well-formed, but I'm guessing it's a duplicate of this?: #212

your qa is the giblib can build ipa.but the doc not see the github action build ipa

**Comment by webbertakken** [comment]
Are you saying that the documentation does not mention that the github action is able to build the `.ipa` file, while it can?

**Comment by matrix3d** [comment]
> Are you saying that the documentation does not mention that the github action is able to build the `.ipa` file, while it can?

yes

**Comment by webbertakken** [comment]
Good point. We should probably add this to our docs somehow to prevent confusion.

**Comment by davidmfinol** [comment]
The unity-builder action can only generate an xcode project; it can't build the .ipa.
To build the .ipa, you need to invoke xcode on mac-os.
We recommend doing this through fastlane, and we have some docs now that show how to use fastlane to build the .ipa and upload it to the App Store: https://game.ci/docs/github/ios
