### ISSUE TITLE
How to sign ipa after using unity-builder

### ISSUE THREAD

**Issue by uchar** [game-ci/unity-builder#212]
I found a utility for uploading .ipa to apple store connect 

`xcrun altool --upload-app -t ios -f "$IPA_PATH" -u "$APP_STORE_CONNECT_USERNAME" -p "$APP_STORE_CONNECT_PASSWORD"`

But before upload, it should be signed using apple certificates.  I'm lost here. for android, we have some parameters about the key store but for iOS I can't find any.

Can someone help me in the right direction?

**Comment by webbertakken** [comment]
Maybe this [part](https://game.ci/docs/gitlab/ios) of the gitlab docs could help a bit.

**Comment by uchar** [comment]
From what I saw the output of the build is an ipa file. So I have a question, does the builder generate xcode project or I have to update xcode project manually and push it to git every time I change the project?

**Comment by davidmfinol** [comment]
@uchar The builder generates the xcode project, so you should not include the xcode project in git.

After using builder to generate the xcode project, you need to build the .ipa and upload to app store connect. You could manually run xcode and use that utility you mentioned. But I think it would be easier/better to use [fastlane](https://fastlane.tools/), like the docs that @webbertakken linked suggest.

**Comment by uchar** [comment]
@davidmfinol Does the builder only create xcode project or build it too?

From my tests the output is an ipa file, So does this mean  the build step in the fastlane which is suggested unnecessary and we only need the upload line? Or we need it for some signing stuffs 🤔

I think there is  redundant and extra steps which is very time consuming is going on here

**Comment by davidmfinol** [comment]
It only creates the xcode project. 
Where are you seeing the .ipa created?

**Comment by uchar** [comment]
@davidmfinol Yeah you are right, It was my mistake
