### ISSUE TITLE
Building using a custom command (not a method, but a script)

### ISSUE THREAD

**Issue by mikeage** [game-ci/unity-builder#217]
**Context**

I'm interested in using the unity-builder images + github action, but instead of building my project from a static method, I need to call a rather overly complicated build script (legacy...). Is there any way to override the entrypoint.sh that calls unity, and instead, call my own script (which will eventually call unity itself)

**Suggested solution**

A generic "command line" option

**Considered alternatives**

I could build my own image and/or action, but I want to leverage the packaging and activation code from game-ci

**Additional details**

**Comment by webbertakken** [comment]
Sure. You can specify the [buildMethod](https://game.ci/docs/github/builder#buildmethod) without doing all kinds of customisations.

**Comment by mikeage** [comment]
I'm experimenting with that now, but buildMethod means I'm already going into Unity, etc; is there any way to just call a shell script / python script instead? Ideally, I'd like to do this before touching any of the actual sources.

**Comment by webbertakken** [comment]
Indeed. Currently there is no way to call a custom shell script inside the container.

Could you please describe your use case for this?

**Comment by mikeage** [comment]
Mostly it relates to a build system that's implemented either outside of C# completely (including a bit of pre-processing, the unity invocation, and then a bunch of packaging / rearranging tasks) or one that's in C# but not in a single function (i.e., there's a menu option added with a custom function that reads a bunch of other config data and then invokes the eventual build). The "standard" unity options are not all used, and there's also some other packaging code that still needs to be added to our single build function. Rather than rewrite this all, I was hoping to be able to just invoke our script, and leverage the unity-builder simply for the authentication code and the actual packaging of unity itself.

**Comment by webbertakken** [comment]
I don't know what "a build system" does for you and I'm not sure if i'm getting a great idea of your use case from your comment above.

Are you able to run your original script from a build [preprocessor](https://docs.unity3d.com/ScriptReference/Build.IPreprocessBuildWithReport.html)

**Comment by mikeage** [comment]
Possibly; honestly, I'm kind of new to Unity development in general, and still figuring out what's what. I'm trying to avoid duplication where possible; I probably could wrap everything into a single function, but I was hoping not to need to. That said, I don't really have the experience to make a persuasive argument as to whether my case is common or atypical. For now, I'll probably do the best I can do put the important parts in C#, and hope that's enough (production releases will still be built locally for licensing reasons; this is mostly for testing PRs).

Thanks

**Comment by webbertakken** [comment]
Just to be clear, I'm not suggesting to rebuild a legacy build step in C# per se.

You may also consider invoking python from within mentioned preprocessor and wait for some trigger that happens after its completion.
