### ISSUE TITLE
Files created by the build are owned by root, not "runner"

### ISSUE THREAD

**Issue by mikeage** [game-ci/unity-builder#219]
**Bug description**

After building using the unity-builder github actions, the output files are owned by `root.root` instead of `runner.docker` like the files in git.

**How to reproduce**

Build.

**Expected behavior**

Files can be modified by the github actions

**Additional details**

The root cause here is that my build doesn't build to build/${{ targetPlatform }}/${{ targetPlatform}}.$EXTENSION, but somewhere else, and so I want to move the output around afterwards in the github workflow rather than in the build function, but I can't because of permissions. But it seems like, in general, this would be a better practice to run `chown` within the docker before finishing.

**Comment by webbertakken** [comment]
This is a tricky one. `chown` to whom?

Docker images are not exclusively used on GitHub, but also on Gitlab, CircleCI, Travis, Jenkins, Azure pipelines, Bamboo, and more.

**Comment by mikeage** [comment]
Good point. I probably should have opened this on the GH action. We can get the name, though, by passing in the result of `$(whoami)` or `$(id)`. 

From the workflow, while we have permissions to delete the files, a chown (or for that matter, chmod, which is what I really need) failed with "permission denied".

**Comment by Bradshaw** [comment]
Does this issue also happen in other CI tools (as mentioned these images are also used on GitLab, CircleCI, etc...) ?

**Comment by Bradshaw** [comment]
Basically: If this issue only affects GitHub Actions self-hosted runners, maybe a simple `chown-files` action would be sufficient to fix the problem.
But if other tools are also affected, then the fix has to happen here, and it has to not just be #141, but also be compatible with #165

**Comment by Bradshaw** [comment]
Okay, I had a little problem re-implementing #141, the license activation step was tripping up because the runner user's $HOME wasn't set correctly.
Setting it manually to "/github/home" solves this issue: https://github.com/game-ci/unity-builder/compare/main...Bradshaw:fix-root-files-and-android

I'm now taking a look at the sdkmanager issue, and will try to solve it in a way that doesn't require running as root
