### ISSUE TITLE
Il2CPP Compiler Configuration Change 

### ISSUE THREAD

**Issue by Warhammer4000** [game-ci/unity-builder#221]
**Context**
In one of my projects I found out for whatever reason if I select master on release for builds some features work weirdly (Keyboard) . But it's fixed if I use release mode.
![Capture](https://user-images.githubusercontent.com/12670678/108955550-8f869300-7698-11eb-8c35-351bd9b8469c.PNG)

When I get artifacts out of CI builds the same issue returns and I'm assuming CI builds the apk using master configuration 
![Capture](https://user-images.githubusercontent.com/12670678/108955691-cd83b700-7698-11eb-8c13-248154a95200.PNG)

**Suggested solution**
It'd be great if we could select compiler configuration from the builder just like we do for android appbundles. something like 

![Capture](https://user-images.githubusercontent.com/12670678/108956177-88ac5000-7699-11eb-873e-b8450a287a49.PNG)

**Considered alternatives**
For now I've building for this project manually.

**Additional details**
I think this feature would be a great addition as fixing compiler configuration to master would eventually break a lot of things in the future as it strips out a lot of things that it probably shouldn't.

**Comment by webbertakken** [comment]
As with all things that are added to the actions or the images, we'll need to be objective about additions.

Before we introduce another parameter, we will first need to know what it does and we will need to know exactly why this happens.

Without this knowledge, we might be introducing backward incompatible changes or even breaking changes for others.

**Comment by davidmfinol** [comment]
The C++ compiler configuration is set in your project's Player Settings, not the Build Settings.
The unity-builder action should use whatever is in your `<projectPath>/ProjectSettings/ProjectSettings.asset` file, but if you REALLY want to ensure that it uses the correct compiler configuration, you could use a `customBuildMethod` that invokes [PlayerSettings.SetIl2CppCompilerConfiguration](https://docs.unity3d.com/ScriptReference/PlayerSettings.SetIl2CppCompilerConfiguration.html).

**Comment by Warhammer4000** [comment]
> The C++ compiler configuration is set in your project's Player Settings, not the Build Settings.
> The unity-builder action should use whatever is in your `<projectPath>/ProjectSettings/ProjectSettings.asset` file (search for `il2cppCompilerConfiguration`, which should have `Android: 1`), but if you REALLY want to ensure that it uses the correct compiler configuration, you could use a custom `buildMethod` that invokes [PlayerSettings.SetIl2CppCompilerConfiguration](https://docs.unity3d.com/ScriptReference/PlayerSettings.SetIl2CppCompilerConfiguration.html).

I agree that the build should address whatever is on projectsetting.asset 
Custom Build Method is something I didn't think of. I think I'll go for that. In case I do find anything new will update here.
