### ISSUE TITLE
Retry license check on 504 gateway timeout

### ISSUE THREAD

**Issue by mastef** [game-ci/unity-builder#229]
We frequently get a 504 gateway timeout answer from the unity license servers when checking the professional license. Which kills the whole build, and it has to be restarted again ( takes about 7 minutes to get to that point )

It would be great if the license check could retry a few more times on a clear http failure such as 504 gateway timeout.

**Comment by mastef** [comment]
In the logs we have : 

```

LICENSE SYSTEM [2021315 14:14:44] Received https://license.unity3d.com/update/poll?(serial removed)

LICENSE SYSTEM [2021315 14:14:44] Headers:
    HTTP/1.0 503 Service Unavailable
    Cache-Control: no-cache
    Connection: close
    Content-Type: text/html
    


LICENSE SYSTEM [2021315 14:14:44] Error fetching https://license.unity3d.com/update/poll?(serial removed)
Cancelling DisplayDialog: Information There was a problem communicating with the license server. Would you like to do a manual activation instead?
This should not be called in batch mode.
 
(Filename: ./Editor/Platform/Linux/EditorUtility.cpp Line: 274)

Unclassified error occured while trying to activate license.
Exit code was: 1
Error: The process '/usr/bin/docker' failed with exit code 1
```

So we could do a lookup for `503 Service Unavailable` and then retry the whole step.

E.g. after https://github.com/game-ci/unity-builder/blob/4fde4e47b6d27fc29af48a272f74ddce5b43e5a9/dist/steps/activate.sh#L43 something like : 

```bash
GATEWAY_ERROR=$(echo $ACTIVATION_OUTPUT | grep -e '503 Service Unavailable' -e '502 Bad Gateway' | wc -l)
```

And then
```bash
  if [[ $GATEWAY_ERROR -eq 1 ]]; then
    UNITY_EXIT_CODE=-2
  fi;
```
to restart the script with a delay? Something like that

**Comment by mastef** [comment]
Or even a lookup for `There was a problem communicating with the license server.`

**Comment by webbertakken** [comment]
That could work. We're open for PRs if someone comes up with a clean solution for this.

**Comment by webbertakken** [comment]
Closing for lack of interest by community.

**Comment by mastef** [comment]
@webbertakken haven't seen these recently. Once there's more of them again we could come back to this.

**Comment by webbertakken** [comment]
A retry mechanism is possible, but it didn't seem very high priority, but the number of responses to this thread.

We're always open for suggestions and PRs of course; closing this ticket by no means is meant to block anyone from improving the status quo :)

**Comment by ErcinDedeoglu** [comment]
`12:53:34 Step 5/15: WebGL - EXEC (LICENSE) (Command Line)
12:53:34   Starting: /opt/buildagent/temp/agentTmp/custom_script15947779215146769774
12:53:34   in directory: /opt/buildagent/work/a0cf9f7531cf2be
12:53:34   Unity Editor version:    2020.3.43f1 (75bff06b76bf)
12:53:34   Branch:                  2020.3/staging
12:53:34   Build type:              Release
12:53:34   Batch mode:              YES
12:53:34   System name:             Linux
12:53:34   Distro version:          #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023
12:53:34   Kernel version:          5.4.0-148-generic
12:53:34   Architecture:            x86_64
12:53:34   Available memory:        32112 MB
12:53:34   [LicensingClient] Channel doesn't exist: "LicenseClient-root"
12:53:34   [Licensing::Module] Successfully launched the LicensingClient (PId: 48)
12:53:35   [SignatureVerifier] Application signature verification not supported on this platform.
12:53:35   [Licensing::Module] Successfully connected to LicensingClient on channel: "LicenseClient-root" (connect: 0.61s, validation: 0.07s, handshake: 0.00s)
12:53:35   [Licensing::Module] Connected to LicensingClient (PId: 48, launch time: 0.00, total connection time: 0.68s)
12:53:35   Entitlement-based licensing initiated
12:53:35   [LicensingClient] Licenses updated successfully
12:53:36   [UnityConnectServicesConfig] config is NOT valid, switching to default
12:53:39   User **@**.com logged in successfully
12:53:40   
12:53:40   LICENSE SYSTEM [2023512 12:53:40] Starting license activation with account **@**.com
12:53:40   
12:53:40   
12:53:40   LICENSE SYSTEM [2023512 12:53:40] Opening https://license.unity3d.com/update/poll?cmd=9&tx_id=***&(serial removed)
12:53:40   
12:53:40   LICENSE SYSTEM [2023512 12:53:40] Posting <?xml version="1.0" encoding="UTF-8"?><root><SystemInfo><IsoCode>C.UTF</IsoCode><UserName>(unset)</UserName><OperatingSystem>Linux 5.4 Ubuntu 18.04 64bit</OperatingSystem><OperatingSystemNumeric>504</OperatingSystemNumeric><ProcessorType>Intel(R) Xeon(R) Platinum 8280L CPU @ 2.60GHz</ProcessorType><ProcessorSpeed>2593</ProcessorSpeed><ProcessorCount>8</ProcessorCount><ProcessorCores>8</ProcessorCores><PhysicalMemoryMB>32112</PhysicalMemoryMB><ComputerName>***</ComputerName><ComputerModel>PC</ComputerModel><UnityVersion>2020.3.43f1</UnityVersion><SupportedLicenseVersion>6.x</SupportedLicenseVersion></SystemInfo><License id="Terms"><MachineID Value="***=" /><MachineBindings><Binding Key="1" Value="***" /><Binding Key="2" Value="***" /></MachineBindings><UnityVersion Value="2020.3.43f1" /></License></root>
12:53:40   
12:54:01   
12:54:01   LICENSE SYSTEM [2023512 12:54:1] Headers:
12:54:01   
12:54:01   
12:54:01   LICENSE SYSTEM [2023512 12:54:1] Error fetching https://license.unity3d.com/update/poll?cmd=9&tx_id=***&(serial removed)
12:54:01   Cancelling DisplayDialog: Information There was a problem communicating with the license server. Would you like to do a manual activation instead?
12:54:01   This should not be called in batch mode.
12:54:01   Process exited with code 1
12:54:01   Process exited with code 1 (Step: WebGL - EXEC (LICENSE) (Command Line))
12:54:01   Step WebGL - EXEC (LICENSE) (Command Line) failed`
