### ISSUE TITLE
Addressables/Localization don't work after build

### ISSUE THREAD

**Issue by kreghek** [game-ci/unity-builder#230]
**Bug description**

I used localization package in my test project. It has one scene and one button with localized string. It work fine in editor and after local build under Windows64. But button is not localized when project is built via unity-builder.

**How to reproduce**

- Create new project.
- Add a buton. Add the localization package. Add LocalizaedString to the button. It's better to use Unity guide https://docs.unity3d.com/Packages/com.unity.localization@0.10/manual/index.html?_ga=2.252199945.1227570470.1616037925-610300725.1603169169
- Build via unity-builder in Github Actions.
- See the button is not localized.

There is my repository with the test project and build workflow:
https://github.com/kreghek/Zilon_Roguelike/tree/fix-997-localization-recreate-2/LocalizationTestProject

**Expected behavior**

The localization works.

**Additional details**

Post in Unity Community Forum
https://forum.unity.com/threads/localization-dont-work-in-windows64-build.1075873/

**Comment by webbertakken** [comment]
Currently you may have to create a custom build script (or duplicate the default build script) to execute these two lines before running the build itself:

```csharp
AddressableAssetSettings.CleanPlayerContent();
AddressableAssetSettings.BuildPlayerContent();
```

We're looking into ways of how to integrate this in the default build script.

The options are:

- Adding a flag in unity-builder that will inject this code conditionally
- Running the code always, if addressables namespace is available (somehow)

In the meantime, the above solution should work.

**Comment by sbergen** [comment]
> * Running the code always, if addressables namespace is available (somehow)

If you add an asmdef for the default build script, you can use [Version Defines](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html#define-symbols) on the addressables package.

**Comment by kreghek** [comment]
> Currently you may have to create a custom build script (or duplicate the default build script) to execute these two lines before running the build itself:
> 
> ```cs
> AddressableAssetSettings.CleanPlayerContent();
> AddressableAssetSettings.BuildPlayerContent();
> ```
> 
> We're looking into ways of how to integrate this in the default build script.
> 
> The options are:
> 
> * Adding a flag in unity-builder that will inject this code conditionally
> * Running the code always, if addressables namespace is available (somehow)
> 
> In the meantime, the above solution should work.

Thank you. Can you show an example of default build script and Github Actions workflow? Where I can get it?

**Comment by sbergen** [comment]
@kreghek I implemented calling that conditionally (based on whether or not the addressables packages is used) in the PR referenced above. You can try running the action with `b667be75b1d0c2496fd884e35368e1c5bf1a8533` to see if it works for you. Or you can take a look at the PR contents to see how the default build script works.

Unity is saying
> We have disabled automatic asset bundle building. That used to happen when you built the player, or entered play mode in "packed mode". This is no longer the case. You must now select "Build->Build Player Content" from the Addressables window, or call AddressableAssetSettings.BuildPlayerContent(). We did this because we determined that automatic building did not scale well at all for large projects.

So it while it apparently works well enough for smaller projects, it might not be the best approach for larger projects. But it's likely that larger projects would be using a custom build script anyway...

**Comment by webbertakken** [comment]
Assuming this is resolved. It will be released with the upcoming version. in the meantime you can use the hash mentioned above.

**Comment by kreghek** [comment]
@sbergen I should just create `Builder` class with those two lines and place it in `Assets/Editor`? How to use it during the build in GH Actions?

**Comment by sbergen** [comment]
> @sbergen I should just create `Builder` class with those two lines and place it in `Assets/Editor`? How to use it during the build in GH Actions?

You can either start using a newer revision of the action, or implement a fully custom build method, which calls those methods, **and also** `BuildPipeline.BuildPlayer`. It needs to be a static method taking no arguments, and can be specified with the `buildMethod` argument.

And example, which builds documentation, but **doesn't** actually do a Unity build:
https://github.com/sbergen/Responsible/blob/main/.github/workflows/main.yml#L141 and
https://github.com/sbergen/Responsible/blob/main/Assets/Responsible/EditorSetup/ContinuousIntegration.cs#L34

**Comment by kreghek** [comment]
Cool! It works! @sbergen Thank you!

I changed my build workflow as shown below:
```
uses: game-ci/unity-builder@224f973562d7dc72505715af6c034f0eb5298069
```
