### ISSUE TITLE
Linux IL2CPP and WebGL builds fail if using the wrong package

### ISSUE THREAD

**Issue by davidmfinol** [game-ci/unity-builder#232]
If the mac or windows LinuxIL2CPP package is used, the LinuxIL2CPP and WebGL builds fail on our linux-based images.

We can check `Packages/manifest.json` for `com.unity.toolchain.macos-x86_64-linux-x86_64` and `com.unity.toolchain.win-x86_64-linux-x86_64`, and if we find them, temporarily replace them with `com.unity.toolchain.linux-x86_64`.

Details on the packages found on [the Unity forums](https://forum.unity.com/threads/linux-il2cpp-cross-compiler-packages-now-available-in-preview.975693/).
https://github.com/game-ci/docker/issues/96 for reference.

**Comment by webbertakken** [comment]
> As a fix on the Unity Builder side, we could maybe add some logic that will check which package is being used for Linux IL2CPP and WebGL builds, and make a temporary change to use the correct dependency during the build.

I'm a bit blown away by the fact that this indeed seems to be necessary. I would expect from Unity that they provide a package that resolves the right dependencies for the OS that installs the packages. Much like how in the JavaScript world, packages can contain OS-specific bindings, that help solve this very problem.

Does anyone know if it is possible to host some kind of meta package that could do this for us, so we can solve the problem for everyone, and on less localised level?

**Comment by webbertakken** [comment]
Seems to have been solved in https://forum.unity.com/threads/linux-il2cpp-cross-compiler-packages-now-available-in-preview.975693/page-2#post-7972122
