### ISSUE TITLE
How can I, from build pipeline, disable compression, in player "Publishing Settings" , Compression Format

### ISSUE THREAD

**Issue by montao** [game-ci/unity-builder#240]
My build is created (WebGL) as an artifact but when I try to run it I get an error message 
`unityFramework is not defined at HTMLScriptElement.r.onload`
I want to try and disable compression because that worked from my manual / local build. Can it be done?

**Comment by davidmfinol** [comment]
Unity Builder will use whatever is in your `<projectPath>/ProjectSettings/ProjectSettings.asset`
To disable compression, just make sure you have `webGLCompressionFormat: 2` in there.

**Comment by montao** [comment]
Thanks, now it worked @davidmfinol

**Comment by pisanuw** [comment]
Is it possible to override the ProjectSettings using the "customParameters" in the yaml file?
