### ISSUE TITLE
hasAnyVersionTags not counting semver tags that doesn't start with 'v'

### ISSUE THREAD

**Issue by elmernocon** [game-ci/unity-builder#242]
**Bug description**

**How to reproduce**

Create tags that doesn't start with `v`. i.e. `0.0.1`, `1.0.0`, `1.0`, etc.

```bash
git tag --list
```

```
1
1.2
1.2.3
11.11.11
2,2,2
v0HELLO
v1
v1.2
v1.2.3
v11.11.11
x1.0.0
```

[Current](https://github.com/game-ci/unity-builder/blob/398eda622fffdac0b8e33e01f21c4c47fe24a955/src/model/versioning.ts#L270)
```bash
git tag --list | grep v[0-9]*
```
```
v0HELLO
v1
v1.2
v1.2.3
v11.11.11
```

**Expected behavior**

```bash
git tag --list | grep '^v\?[0-9]\+\(\.[0-9]\+\)\?\(\.[0-9]\+\)\?$'
```
```
1
1.2
1.2.3
11.11.11
v1
v1.2
v1.2.3
v11.11.11
```

```diff
-      input: Buffer.from('git tag --list --merged HEAD | grep v[0-9]* | wc -l'),
+      input: Buffer.from('git tag --list --merged HEAD | grep '^v\?[0-9]\+\(\.[0-9]\+\)\?\(\.[0-9]\+\)\?$' | wc -l'),
```

Or more permissive:

```bash
git tag --list | grep '^v\?[0-9]\+'
```
```
1
1.2
1.2.3
11.11.11
2,2,2
v0HELLO
v1
v1.2
v1.2.3
v11.11.11
```

```diff
-      input: Buffer.from('git tag --list --merged HEAD | grep v[0-9]* | wc -l'),
+      input: Buffer.from('git tag --list --merged HEAD | grep '^v\?[0-9]\+' | wc -l'),
```

**Comment by GabLeRoux** [comment]
Related code:
https://github.com/game-ci/unity-builder/blob/main/src/model/unity-versioning.ts
https://github.com/game-ci/unity-builder/blob/main/src/model/unity-versioning.test.ts

**Comment by GabLeRoux** [comment]
Related code:
https://github.com/game-ci/unity-builder/blob/main/src/model/versioning.ts
https://github.com/game-ci/unity-builder/blob/main/src/model/versioning.test.ts
