### ISSUE TITLE
AWS tasks don't stop if the previous step fails

### ISSUE THREAD

**Issue by edencakir** [game-ci/unity-builder#271]
**Context**

The whole code assumes all of the previous steps are completed successfully, and not aborting the execution of the job if any of the steps above fail. 

Ex: the task below couldn't download the git repo but still tries to cd into the folder and rename it, try to build it, etc. until all of the tasks are completed (or failed) in order.

```
...
 (1/2) Installing unzip (6.0-r8)
(2/2) Installing zip (3.0-r9)
Executing busybox-1.32.1-r6.trigger
OK: 6 MiB in 16 packages
/bin/sh: cd: line 4: can't cd to Library: No such file or directory
zip error: Nothing to do! (try: zip -q -r build-2-iOS-6yTb.zip . -i build/iOS/*)
mv: can't rename 'build-2-iOS-6yTb.zip': No such file or directory
End of task logs
Task has finished successfully
Cleanup complete
Starting part 4/4 (upload build to s3)
Creating worker cluster...
Creating cleanup cluster...
Worker cluster created successfully (skipping wait for cleanup cluster to be ready)
Task is starting on worker cluster
Task is running on worker cluster
Task status is STOPPED
...

```

**Suggested solution**
Abort the mission if something goes wrong.

**Comment by webbertakken** [comment]
@frostebite could you have a look at this issue?

I believe this has been solved since right?

**Comment by frostebite** [comment]
Should be resolved in latest.
