### ISSUE TITLE
manifest for unityci/editor:2020.3.4f1c-webgl-0 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by limz8319** [game-ci/unity-builder#307]
**Bug description**

**How to reproduce**

-

**Expected behavior**

**Additional details**

**Comment by limz8319** [comment]
this image not found on docker hub

**Comment by webbertakken** [comment]
There is no such version (`2020.3.4f1c`) [made available](https://unity3d.com/get-unity/download/archive) by Unity.

Did you mean `2020.3.4f1` (without the c)?

**Comment by limz8319** [comment]
Run game-ci/unity-builder@v2
Warning: 
      Library folder does not exist.
      Consider setting up caching to speed up your workflow,
      if this is not your first build.
    
false

/usr/bin/sh
0
0

5

Generated version 0.0.5 (no version tags found).
Using android versionCode 5
Building locally
/usr/bin/docker build /home/runner/work/_actions/game-ci/unity-builder/v2/dist --file /home/runner/work/_actions/game-ci/unity-builder/v2/dist/Dockerfile --build-arg IMAGE=unityci/editor:2020.3.4f1c-webgl-0 --tag unity-builder:2020.3.4f1c-webgl-0
Sending build context to Docker daemon  24.21MB

Step 1/16 : ARG IMAGE
Step 2/16 : FROM $IMAGE
manifest for unityci/editor:2020.3.4f1c-webgl-0 not found: manifest unknown: manifest unknown
Error: The process '/usr/bin/docker' failed with exit code 1

**Comment by limz8319** [comment]
The error message is as follows

**Comment by webbertakken** [comment]
Could you please update your opening post with details about what your workflow looks like (the part that configures builder only)?

**Comment by limz8319** [comment]
name: Build project

on: [push, pull_request]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - WebGL # WebGL.
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

**Comment by webbertakken** [comment]
Note that you can properly format yaml files using triple backticks (`) before and after, like so:

![image](https://user-images.githubusercontent.com/20756439/147107485-412ef975-807e-405c-bf8b-d29eff04ec3e.png)

result:

```yaml
my:
  yaml
```

As for your issue, could you also please share the contents of  `ProjectSettings/ProjectVersion.txt` inside your project?

It looks like the version is auto-detected, but the specified unity version does not exist publicly.

**Comment by limz8319** [comment]
emmmm One character too many in ProjectSettings/ProjectVersion.txt，I fixed it
