### ISSUE TITLE
build success but when play in  window , android it show black screen

### ISSUE THREAD

**Issue by dungnguyen2304** [game-ci/unity-builder#316]
**Bug description**

I have build simple project only have cube and plane + add movement script on cube, I have build to webGL, android , window build success but when launch the app only have black screen , I have use unity 2020.3.3 
**How to reproduce**

-

**Expected behavior**

**Additional details**

**Comment by davidmfinol** [comment]
With such a simple project, can you share a link to the repo so we could take a look?

**Comment by webbertakken** [comment]
Closing until we have steps to reproduce this.
