### ISSUE TITLE
Building the standalone OSX app fails

### ISSUE THREAD

**Issue by vinaysshenoy** [game-ci/unity-builder#318]
I've been trying to set up `game-ci` to use with our project. However, I am having some trouble getting the project to build. Adding relevant information below:

Unity3D version: `2020.3.11f1`
Runner OS: `ubuntu-latest`

# Action snippet

```yaml
- name: Build project
  uses: game-ci/unity-builder@v2
  env:
    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
  with:
    projectPath: qweebi-unity
    targetPlatform: StandaloneOSX
    buildName: Qweebi-MacOS.app
```

The build fails with the following error snippet:

```sh
2022-01-13T13:55:49.2373786Z Start importing Assets/_Art/HDRI/aerodynamics_workshop_16k.hdr using Guid(d61d87ff956983041a99faf0c7166812) Importer(-1,00000000000000000000000000000000) Killed
2022-01-13T13:55:49.3067839Z Build failed, with exit code 137
2022-01-13T13:55:50.0275073Z chmod: cannot access '/github/workspace/build/StandaloneOSX/StandaloneOSX.app/Contents/MacOS/*': No such file or directory
```

Can someone point me as to what I am doing wrong here?

**Comment by vinaysshenoy** [comment]
Alright, I tried building a Win64 target instead, and it failed at importing the same asset.

```shell
Start importing Assets/_Art/HDRI/aerodynamics_workshop_16k.hdr using Guid(d61d87ff956983041a99faf0c7166812) Importer(-1,00000000000000000000000000000000) Killed
Build failed, with exit code 137
```

The actual problem might be with trying to import that particular asset on the Unity linux editor. Would someone have seen something like this before?

**Comment by vinaysshenoy** [comment]
Well, we figured out what the problem was. That particular asset was just too large for the GitHub action runners. Rescaling it to 4k worked and we were able to build.

Closing this issue now.

**Comment by webbertakken** [comment]
Thanks for reporting back your solution as well!

Do you know what made it too large for the runner? Was it running out of memory or disk space or other?

**Comment by vinaysshenoy** [comment]
@webbertakken I'm afraid I don't know the actual reason since the build logs did not actually give a detailed error message and the error was a generic "Import failed".

This was just something we tried and it turned out was the right solution.
