### ISSUE TITLE
Builds for MacOS broken for (at least) version 2021.2.*

### ISSUE THREAD

**Issue by grascm** [game-ci/unity-builder#320]
**Bug description**

Build target StandaloneOSX is broken:
```
2022-01-20T12:42:47.5946800Z *** Tundra build failed (19.30 seconds), 368 items updated, 370 evaluated
2022-01-20T12:42:47.5950193Z Building build/StandaloneOSX/StandaloneOSX.app/Contents/Frameworks/libmono-native.dylib failed with output:
2022-01-20T12:42:47.5951549Z The properties of source file /opt/unity/Editor/Data/PlaybackEngines/MacStandaloneSupport/Variations/macos_x64ARM64_player_nondevelopment_mono/UnityPlayer.app/Contents/Frameworks/libmono-native.dylib could not be retrieved: No such file or directory
```

**How to reproduce**

Build any project with `targetPlatform` set to `StandaloneOSX` and unity version `2021.2.*`

**Expected behavior**

Build succesfull

**Additional details**

Required path exists in wrong case:
`/opt/unity/Editor/Data/PlaybackEngines/MacStandaloneSupport/Variations/macos_x64arm64_player_nondevelopment_mono/`

Official unity forums have bug description and workaround:
[https://forum.unity.com/threads/linux-command-line-build-of-macos-has-wrong-mono-path.1200499/](https://forum.unity.com/threads/linux-command-line-build-of-macos-has-wrong-mono-path.1200499/)

**Comment by webbertakken** [comment]
Thank you very much for your bug report. Especially also for linking relevant information!

Ideally we would republish the images after Unity fixes the bug, but we'll see what we can do if this doesn't get solved by them short term.

**Comment by rcoppy** [comment]
Hello! Chiming in to say Mac builds are failing for me, too, with an error quite similar to that of @grascm :
```
Building /github/workspace/build/StandaloneOSX/StandaloneOSX.app/Contents/Frameworks/UnityPlayer.dylib failed with output:
System.ArgumentException: Copy() called on path that doesnt exist: /opt/unity/Editor/Data/PlaybackEngines/MacStandaloneSupport/Variations/macos_x64ARM64_player_nondevelopment_mono/UnityPlayer.app/Contents/Frameworks/UnityPlayer.dylib
   at NiceIO.NPath.CopyWithDeterminedDestination(NPath destination, Func`2 fileFilter)
   at NiceIO.NPath.Copy(NPath dest, Func`2 fileFilter)
   at NiceIO.NPath.Copy(NPath dest)
   at MacOSCodeSignDylibCopy.Run(CSharpActionContext ctx, SignFlags signFlags)
```
I'll try using the fix linked to in the Unity forum thread. 
Thanks!

**Comment by ViMaSter** [comment]
After attempting to upgrade a build pipeline from `2020.3.15f2` to `2021.2.8f1`, I'm unfortunately [running into this issue as well](https://github.com/ViMaSter/GG-JointJustice-Unity/runs/4958379506?check_suite_focus=true).
As you can see from [the full run](https://github.com/ViMaSter/GG-JointJustice-Unity/actions/runs/1753225114), Windows and Linux builds still pass and the exact same project using `2020.3.15f2` [succeeded building previously](https://github.com/ViMaSter/GG-JointJustice-Unity/actions/runs/1733612154).

Any updates on this?

**Comment by rcoppy** [comment]
> 

It's a huge bummer, yeah;  but unfortunately I think it's a blocking issue on the Unity engineering side of things, not game-ci--which means it's going to be a minute before it gets fixed 😢 one thing you can do is open a bug report with Unity themselves through their reporting system; if enough people do that this issue might get higher priority. In the meantime, it might be better to roll back to 2020 LTS. Good luck!!

**Comment by rcoppy** [comment]
> Did anyone get the suggested fix to work? We might be able to apply it on GameCI side if it works.
> 
> Open for PRs

Unfortunately I don't have a ton of experience with docker and I'm on a rather tight deadline, so I haven't had the time to dive in and figure it out--maybe in a bit! 🙏

**Comment by davidmfinol** [comment]
@jsm174 Here is where the linux images are created: https://github.com/game-ci/docker/blob/main/images/ubuntu/editor/Dockerfile
