### ISSUE TITLE
Automatically Resolve Vulnerabilities Detected by Yarn

### ISSUE THREAD

**Issue by AndrewKahr** [game-ci/unity-builder#321]
**Bug description**

When commiting to git, it automatically compiles and runs tests, but I see yarn pointing out that there are vulnerabilities in several packages:
`16 vulnerabilities found - Packages audited: 844
Severity: 14 Moderate | 2 High`

Should we be bumping the versions up with yarn audit?

**Comment by davidmfinol** [comment]
Dependabot automatically raises PR for vulnerabilities: https://github.com/game-ci/unity-builder/pull/319
I think there may even be a way to have these vulnerability PRs be automatically merged?
I haven't looked into it, but that would be good if so, since it tends to be fairly low priority to try to keep up with the latest versions for security.

**Comment by webbertakken** [comment]
I just merged 2 automated fixes. For the last one we need to update the actions dependencies.

Merging fully automated is possible, but usually you want your pipeline to pass. And we're testing quite a few things (different things per repo) so we'll need to look at how to merge them for each of the repos.

I once looked into how often our actions code path actually hits some of the vulnerabilities, but it's not very often as our logic is not dependent on much of the dependencies code. Even when it is, it's usually used in a controlled environment often making it hard or impossible to abuse the vulnerabilities.

**Comment by davidmfinol** [comment]
We've updated the dependencies so that `yarn audit` no longer detects any vulnerablities.
However, I think it would be good to have fully automated merging for this, so I'll change the label from bug to enhancement.

**Comment by webbertakken** [comment]
This is now part of linting in this repo.
