### ISSUE TITLE
Move additional parameters to the `ImageEnvironmentFactory`

### ISSUE THREAD

**Issue by frostebite** [game-ci/unity-builder#327]
Should we also move this to the `ImageEnvironmentFactory` as well? (also fine in a followup)

_Originally posted by @webbertakken in https://github.com/game-ci/unity-builder/pull/310#discussion_r795213372_

**Comment by webbertakken** [comment]
Added this to the [Roadmap to v3.0.0](https://github.com/orgs/game-ci/projects/4/views/1).

It should become part of the CLIs logic
