### ISSUE TITLE
Does Windows builds support il2cpp?

### ISSUE THREAD

**Issue by jsm174** [game-ci/unity-builder#342]
Looking at https://github.com/game-ci/unity-builder/pull/305 and the [v2.0.0-alpha-14 release](https://github.com/game-ci/unity-builder/releases/tag/v2.0.0-alpha-14), it appears Windows builds should support il2cpp:

```
- Added build tests for windows il2cpp, WSAPlayer, and tvOS in build-test workflow
```

I just tried to build an app with il2cpp and it fails:

```
Asset Pipeline Refresh: Total: 0.266 seconds - Initiated by StopAssetImportingV2(NoUpdateAssetOptions)
DisplayProgressNotification: Build Failed
Error building Player: Currently selected scripting backend (IL2CPP) is not installed.
Unloading 51 Unused Serialized files (Serialized files now loaded: 0)
Unloading 57 unused Assets / (2.1 KB). Loaded Objects now: 9210.
```

It appears to be using `unity-builder:windows-2021.2.8f1-windows-il2cpp-0`

If I switch to mono, the CI works great and a working executable is produced.

Do I need to do something else to get il2cpp working?

**Comment by AndrewKahr** [comment]
There was a bug with the initial rollout of 0.17 images so I don't think the 2021 versions had the modules properly installed. It was sorted out mid deployment so 2020 images started getting the modules. Will need to wait for the next tag to be pushed for the images to be rebuilt with the modules unfortunately.

**Comment by jsm174** [comment]
@AndrewKahr  - Thank you for the info. So you mean I can try again when we have something newer than `editor-2021.2.8f1-0.17.0`?

<img width="1303" alt="Screen Shot 2022-02-22 at 7 34 59 PM" src="https://user-images.githubusercontent.com/1197137/155243350-030bc134-0fd9-42e9-86e9-d0c085a0f597.png">

**Comment by davidmfinol** [comment]
`unity-builder:windows-2021.2.8f1-windows-il2cpp-0` should now be updated by v0.17.2

@jsm174 Are you able to get il2cpp working now?

**Comment by jsm174** [comment]
Hello. I will check. Unfortunately my github actions quota is all used up until the end of the month. I wasn't thinking that mono builds I should just use ubuntu. And with macos being 10x minute multiplier..  arg...

**Comment by jsm174** [comment]
Just wanted to follow up.  I was able to successfully make a windows il2cpp build of our app!

**Comment by davidmfinol** [comment]
Awesome! Closing this issue.
