### ISSUE TITLE
Unclassified error occured while trying to activate license error on every build

### ISSUE THREAD

**Issue by gia-t-mindojo** [game-ci/unity-builder#345]
**Bug description**

Hello!
We are getting `Unclassified error occured while trying to activate license` error on every build since 22 Feb and [this ](https://github.com/game-ci/unity-builder/commit/8e0583a14b173c2a15079ea1fe3d55a5e4af8809)commit. 
Unity version is 2020.3.27f1

![image](https://user-images.githubusercontent.com/74184145/155325830-2b711e1c-850f-4f1d-b533-88926bbe62b1.png)

**How to reproduce**

-Run build with game-ci/unity-builder@main
-Build exits with errors

**Expected behavior**

-Build is successful

**Additional details**

It started happening exactly after [this commit](https://github.com/game-ci/unity-builder/commit/8e0583a14b173c2a15079ea1fe3d55a5e4af8809), 

![image](https://user-images.githubusercontent.com/74184145/155324569-5ac5f21b-4428-435e-bddd-96dd9ea14b3d.png)

This changes cause XML lines of Unity personal license to be written in different lines during this command 

![image](https://user-images.githubusercontent.com/74184145/155324880-ab0129b9-21ff-4fde-9ab8-24df8923240c.png)

Tested to run build from previous commit (game-ci/unity-builder@b94200d3d45b6c3444ef978465d519069c4ade89) and everything works as expected

**Comment by davidmfinol** [comment]
Thanks for raising this issue. I'll submit another PR to allow multi-line specifically for the key that needs it.

**Comment by davidmfinol** [comment]
I believe this should now be fixed with https://github.com/game-ci/unity-builder/pull/346

@gia-t-mindojo Can you confirm?

**Comment by gia-t-mindojo** [comment]
Just tested and everything works well again, thank you for the quick fix @davidmfinol
