### ISSUE TITLE
Does "versioning: Tag" work?

### ISSUE THREAD

**Issue by vitalyk-multinarity** [game-ci/unity-builder#350]
I'm trying to use 'versioning: Tag' in my build for Android target.
Build command seems to be OK:
--env GITHUB_REF=refs/tags/v0.0.0.8
--env VERSION=0.0.0.8
but resulting .apk shows ' versionName='0.1.0''.

Please suggest,
Vitaly

**Comment by davidmfinol** [comment]
`versioning: Tag` still expects [semantic versioning](https://semver.org/), meaning that it expects tags to look like `v<major>.<minor>.<patch>`. Your tag goes to a fourth decimal, so it won't be picked up.

**Comment by vitalyk-multinarity** [comment]
@davidmfinol - thank you, got it.
But even when I used v1.2.3 tag, I still saw versionName='0.1.0'.

**Comment by davidmfinol** [comment]
In your logs, you should be able to search for `COMMAND LINE ARGUMENTS:`, which should then print something like `/opt/unity/Editor/Unity [flags]`. Are you able to see if `-buildVersion` and `-androidVersionCode` match your expected values there?
If so, are you perhaps using a custom build method? Does it apply the version number as shown here?: https://github.com/game-ci/documentation/blob/main/example/BuildScript.cs#L23

**Comment by vitalyk-multinarity** [comment]
Yes, we're using a custom build method, which doesn't use 'buildVersion' for setting version.
Many thanks for your assistance, I'll close this issue as resolved.
