### ISSUE TITLE
workflow depends on its target repo rather than on cloned repo

### ISSUE THREAD

**Issue by gucio321** [game-ci/unity-builder#354]
**Bug description**

Hi!
I created a workflow that pulls the code from some private repository and uploads assets to the public one (the repository workflow is running on).
the problem is that some git commands in unity-builder reffers to workflow's base repository commits

**How to reproduce**
- create repository like game-builds (in my case https://github.com/neonknights/scheme-website)
- create another one with game itself (private)
- in game-build repo create new workflow (like that: https://github.com/neonKnights/sCHEMe-website/blob/main/.github/workflows/release-package.yml)
- in workflow, checkout code from `game` repo
- run unity build
- workflow fails https://github.com/neonKnights/sCHEMe-website/runs/5437854707?check_suite_focus=true

**Expected behavior**

unity-builder should depend on currently cloned repo

**Comment by webbertakken** [comment]
> some git commands in unity-builder reffers to workflow's repository commits

Could you give an indication of what these commands are? It is currently not clear from your steps to reproduce.

**Comment by gucio321** [comment]
@webbertakken thank you for your answer!
The failure says:
```console
Warning: fatal: c09a448c944ac1649eaafe09dd70eb4691214ed6 is neither a commit nor blob

Error: Failed to run "git describe --long --tags --always c09a448c944ac1649eaafe09dd70eb4691214ed6".
 In-command error caught: Error: The process '/usr/bin/git' failed with exit code 128
 ```
`c09a448c944ac1649eaafe09dd70eb4691214ed6` is top commit of my sCHEMe-website repository, but the other one is checked out

**Comment by davidmfinol** [comment]
Hi @gucio321 , I'm trying to understand your use case. Why are you running the workflow from the sCHEMe-website repo instead of the game repo? Wouldn't it be better to have your builds run whenever you commit to the game repo, where you could then upload the build somewhere? That way, you could verify each commit is not breaking your builds, and you could still use the sCHEMe-website workflow to simply download the last build.

**Comment by gucio321** [comment]
well,, it could be a nice workaround, however I'm wondering why this couldn't be done in my current way?

**Comment by davidmfinol** [comment]
> why this couldn't be done in my current way?

I think most people would expect that git commands run relative to the repo running the workflow, not the latest checked-out repo.
With that said, it probably is possible to add an option that would indicate which repo should be used for git commands. But is it worth the added complexity to do so?

**Comment by gucio321** [comment]
> which repo should be used for git commands. But is it worth the added complexity to do so?

IMO it'll not add complexity, it'll just add possibility to change default behaviour. if the user wouldn't specify sucha n option, the default one should be used

**Comment by webbertakken** [comment]
Changing default behaviour with a configurable option by definition increases complexity: increased amount of paths logic can take will have to be tested and maintained.

> well,, it could be a nice workaround, however I'm wondering why this couldn't be done in my current way?

Anything could be done. The reason we're not already doing it your way is that we're following as many best practices as possible. 

I believe the correct etiquette here is that the newly introduced idea is argumented with reasons to change the baseline, not vice versa. Furthermore, following best practices reduces hidden complexity. Therefor I'm inclined to repeat @davidmfinol's questions:

> Why are you running the workflow from the sCHEMe-website repo instead of the game repo? Wouldn't it be better to have your builds run whenever you commit to the game repo, where you could then upload the build somewhere?

**Comment by webbertakken** [comment]
You're very welcome. Thank you as well!
