### ISSUE TITLE
Package mode support

### ISSUE THREAD

**Issue by andywiecko** [game-ci/unity-builder#363]
**Context**

Currently, there  is an upcoming feature for testing Unity packages for https://github.com/game-ci/unity-test-runner/pull/164.
Are there plans to implement support for Unity package builds as well?

**Suggested solution**

Similar solution as in https://github.com/game-ci/unity-test-runner/pull/164.

**Additional details**

This could be very useful for example in the detection of Unity.Editor usage in non-editor assemblies.

**Comment by AndrewKahr** [comment]
Closing this as it is a duplicate of #236
