### ISSUE TITLE
Tags with no leading v not found

### ISSUE THREAD

**Issue by Kacy-Luker** [game-ci/unity-builder#369]
```  static async hasAnyVersionTags() {
    const numberOfCommitsAsString = await System.run('sh', undefined, {
      input: Buffer.from('git tag --list --merged HEAD | grep v[0-9]* | wc -l'),
      cwd: this.projectPath,
      silent: false,
    });
```
https://github.com/game-ci/unity-builder/blob/ca9d445c3cae885bc98615c72d115d348dd827e2/src/model/versioning.ts#L274

The search for tags is only finding tags in the form of {v.#.#.#}. Proposed change to allow tags in for form {#.#.#} to be accepted as well.

**Comment by Kacy-Luker** [comment]
PR to fix this is open.
https://github.com/game-ci/unity-builder/pull/370
Suggested Change
```  static async hasAnyVersionTags() {
    const numberOfCommitsAsString = await System.run('sh', undefined, {
    const numberOfCommitsAsString = await System.run('sh', undefined, {
      input: Buffer.from('git tag --list --merged HEAD | grep v[0-9]* | wc -l'),
      input: Buffer.from('git tag --list --merged HEAD | grep -E "v?[0-9]*" | wc -l'),
      cwd: this.projectPath,
      cwd: this.projectPath,
      silent: false,
      silent: false,
    });
    }); ```

**Comment by webbertakken** [comment]
Recommend simply using v#.# tags like v0.1, which will generate version number `0.1.6` where 6 is the number of commits (squashed PRs) since you've created the tag.
