### ISSUE TITLE
Question: is there a post/article with the best practices for build performance?

### ISSUE THREAD

**Issue by vitalyk-multinarity** [game-ci/unity-builder#375]
I'm trying to improve the performance of my Unity build. 
And while I see some suggestions (like LFS caching) for the checkout step, I couldn't find a best practice article for the build step itself (besides library caching). Any suggestions?

Thank you,
Vitaly

**Comment by davidmfinol** [comment]
I'm not aware of any good articles with regards to build performance.
The only suggestion I can make is to join our discord and ask there: http://game.ci/discord

**Comment by webbertakken** [comment]
At the moment we do not have a step-by-step guide for this, but next to asking questions on discord, I would also recommend having a look at [this example](https://game.ci/docs/github/getting-started#simple-example-with-git-lfs) workflow in our documentation.

**Comment by vitalyk-multinarity** [comment]
> At the moment we do not have a step-by-step guide for this, but next to asking questions on discord, I would also recommend having a look at [this example](https://game.ci/docs/github/getting-started#simple-example-with-git-lfs) workflow in our documentation.

Thank you!
I tried to use LFS caching, based on this and other examples, but my build failed. I suspect it's related to the fact that my project uses submodules, and submodules use LFS as well. 
But unfortunately, I couldn't fix that so far.

**Comment by webbertakken** [comment]
You might wanna check out the sub-modules as well during or right after the initial checkout step.

Then for each submodule you'll have to:
- `git lfs install` 
- `git lfs pull` and 
- apply the caching strategy that you mentioned. (might still work with the actions/cache action)

That sounds like a pretty enterprise level use-case though. 

Unfortunately we'll likely not start documenting such complicated flows however, as in the end it's hard to cover all specifics for all users. I'd like to believe that teams that choose to use a complex workflow like this have a good reason for it (as it's expensive) and will have people that can manage with this added complexity.

**Comment by davidmfinol** [comment]
Closing this issue, as the question has been answered as much as it can be for now.
