### ISSUE TITLE
Separate build artifact for each target platform

### ISSUE THREAD

**Issue by achimmihca** [game-ci/unity-builder#378]
**Context**

We have a working build for different target platforms (Windows, MacOS, Linux, Android, iOS).
Currently, the build artifacts are uploaded as a single archive.

This archive is relatively huge. If someone wants to download only one of the target platforms then there is a lot of waste.

Please find our build configuration here: https://github.com/UltraStar-Deluxe/Play/blob/master/.github/workflows/build-unity-project.yml
A build result can be found here (just ignore the failed build for MacOS): https://github.com/UltraStar-Deluxe/Play/actions/runs/2066616672

**Suggested solution**

I would like to configure the build such that each target platform results in a separate artifact.
Is this possible already?

**Considered alternatives**

Workaround for now: download huge artifact, extract it, throw away unwanted stuff.

**Comment by webbertakken** [comment]
Sure. Try this

```diff
      - uses: actions/upload-artifact@v2
        with:
-         name: Build
+         name: ${{ matrix.targetPlatform }}-build
          path: build
```

**Comment by davidmfinol** [comment]
> Sure. Try this
> 
> ```diff
>       - uses: actions/upload-artifact@v2
>         with:
> -         name: Build
> +         name: ${{ matrix.targetPlatform }}-build
>           path: build
> ```

In addition, I'd also recommend uploading the subfolder insteadof the entire build folder:

```
path: build/${{ matrix.targetPlatform }}
```

**Comment by achimmihca** [comment]
Works like a charm 👍 
Many thanks!
