### ISSUE TITLE
I get some error i think it has to do with readyplayerme

### ISSUE THREAD

**Issue by KennyDevT** [game-ci/unity-builder#379]
Error building Player: BuildFailedException: Build cancelled: Using demo subdomain.

**Comment by webbertakken** [comment]
Since you closed it, would you mind sharing your solution?

**Comment by KennyDevT** [comment]
Well readyplayer.me has this function that activate when you don't have a partner subdomain and you build so I just put in something random in the subhuman and the error stopped
