### ISSUE TITLE
Windows 2021.3.0f1 builds fail

### ISSUE THREAD

**Issue by davidmfinol** [game-ci/unity-builder#386]
**Bug description**

Building on windows with windows images using Unity 2021.3.0f1 fails with this error after many attempts:
```
Aborting batchmode due to fatal error:
Failed to initialize unity graphics.
Editor exited with error(s): Failed to initialize graphics.

Make sure you have DirectX 11 installed, have up to date

drivers for your graphics card and have not disabled

3D acceleration in display settings.
```

**How to reproduce**

- Windows build using Unity 2021.3.0f1: https://github.com/finol-digital/Card-Game-Simulator/runs/6021677123?check_suite_focus=true

**Expected behavior**

Build should succeed

**Additional details**

Builds were working on Windows with Unity 2020.3.30f1

**Comment by davidmfinol** [comment]
I've found that the issue must be with some setting in `ProjectSettings`.
Failing run: https://github.com/davidmfinol/unity-actions-example/actions/runs/2272591954
Changes for that run: https://github.com/davidmfinol/unity-actions-example/commit/fc47f3cde4a2555f1ff7d729b07e6604b5171d51

Now to narrow down which setting caused the issue....

**Comment by davidmfinol** [comment]
I've identified that the issue is with `ProjectSettings/EditorSettings.asset`

Here's the diff where the older version has the issue, but the newer version works ok:
https://github.com/davidmfinol/unity-actions-example/commit/8b523f7e61ad94913a734b6afffc8ada5260366c

Just need to find which specific setting in this file is causing the issue.
Luckily, the file isn't too big, so should be able to figure it out soon.

**Comment by davidmfinol** [comment]
Fixed it by setting `m_RefreshImportMode: 0` in `ProjectSettings/EditorSettings.asset`.

I don't know what `m_RefreshImportMode` is or why it causes this issue, but I guess I'm happy to close this issue now.

**Comment by webbertakken** [comment]
Great! Thanks for sharing that solution with us David!
