### ISSUE TITLE
Self-hosted Win 10: Warning `'gh' is not recognized as an internal or external command`

### ISSUE THREAD

**Issue by Carsten-MaD** [game-ci/unity-builder#390]
**Bug description**

When I try to build a Unity game on a self-hosted Windows 10 runner, I get the following warning message:

```
'gh' is not recognized as an internal or external command,
operable program or batch file.
```

**Workaround**
Installing GitHub CLI for Windows solves the problem.

**Error Log**
```
Run game-ci/unity-builder@v2
Warning: 
      Library folder does not exist.
      Consider setting up caching to speed up your workflow,
      if this is not your first build.
    
Using android versionCode 0
[Client] Error: Command failed: gh auth status -t
'gh' is not recognized as an internal or external command,
operable program or batch file.

Error: Command failed: gh auth status -t
'gh' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by frostebite** [comment]
Thanks for sharing this issue with us. 

You can install gh (GitHub CLI) to unblock this issue immediately. 

I will hotfix this so the check for the GitHub CLI doesn't fail like this shortly and update this ticket.

**Comment by frostebite** [comment]
Should be resolved in `cloud-runner-develop` latest. Will include fix in:
https://github.com/game-ci/unity-builder/pull/387
