### ISSUE TITLE
WebGl builds under local windows - builds in gameci but with errors

### ISSUE THREAD

**Issue by McSwan** [game-ci/unity-builder#391]
**Bug description**

1. I have a blank unity app in 2021 LTS. eg [https://github.com/McSwan/HubTest](https://github.com/McSwan/HubTest)
2. Builds and runs fine in windows. 
3. building in game ci is successful  - [https://github.com/McSwan/HubTest/actions](url)
4. web gl has an error [https://buckettown.s3.ap-southeast-2.amazonaws.com/index.html](url)
5. and there is no error in the windows build

**How to reproduce**
see above

^
-

**Expected behavior**

builds the same as windows
**Additional details**

![image](https://user-images.githubusercontent.com/14303329/165432704-eaec3564-8cb3-479a-83df-b88a19ff803e.png)

![image](https://user-images.githubusercontent.com/14303329/165432747-57fd338d-ad15-4f4e-82c3-798e07645b63.png)

**Comment by McSwan** [comment]
Could be a unity bug and nothing to do with gameci, but thought I'd ask here first.

**Comment by McSwan** [comment]
![image](https://user-images.githubusercontent.com/14303329/165434941-8ea42990-78b5-4da6-8f83-6603f67878e3.png)
"Internal-Error.shader could not be loaded error" in the console.

**Comment by McSwan** [comment]
So it works in unity version 2021.1.24f1, and doesn't work in 2021.2.3f1. So there was a change in between those version that broke webgl. - Don't use anyhting above 2021.1.24f1 to build webgl atm.

**Comment by derfl007** [comment]
We're having a similar problem, the game builds perfectly on windows, but via game-ci a (very important) 2d camera projection texture is missing which makes the game unplayable... After checking it seems we're getting similar error messages

Did you have any problems building with 2021.1.24f1 instead of 2021.2.3f1? Because if that works fine, I might just try it out!

**Comment by McSwan** [comment]
Apparently the URP guys added something that broke linux builds. Unity is investigating.

**Comment by shiena** [comment]
Maybe a related issue.
https://issuetracker.unity3d.com/issues/linux-webgl-build-crashes-every-time-when-using-unity-editor-on-linux

**Comment by McSwan** [comment]
Unity have fixed the bug but haven't got a release for it yet. Need to watch the the bug above ^ for what release has the fix.
Here's the forum post down the bottom
[https://forum.unity.com/threads/memory-access-out-of-bounds-when-running-a-build-for-an-empty-project.1199230/#post-8107895](https://forum.unity.com/threads/memory-access-out-of-bounds-when-running-a-build-for-an-empty-project.1199230/#post-8107895)

**Comment by shiena** [comment]
> Maybe a related issue. https://issuetracker.unity3d.com/issues/linux-webgl-build-crashes-every-time-when-using-unity-editor-on-linux

Unity 2021.3.X / 2022.1.X / 2022.2.X has been updated to fixed in issue tracker.

**Comment by McSwan** [comment]
Has gameci been updated with those versions ?

**Comment by McSwan** [comment]
I tried building it as 2021.3.3f1 - it's still broke, at least as of right now.
 - name: Build Unity Project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: ./
          # unityVersion: 2021.2.3f1
          # unityVersion: 2021.1.24f1
          unityVersion: 2021.3.3f1

**Comment by shiena** [comment]
https://unity3d.com/jp/unity/whats-new/2021.3.3
Unity2021.3.3f1 release notes remain in the Known Issues. Probably fixed in Unity2021.3.4f1.

**Comment by McSwan** [comment]
Tested Unity2021.3.4f1 yesterday, and it wasn't released yet - tested it today and looks like it works. Yay!

**Comment by davidmfinol** [comment]
Closing this issue, as it seems to be fixed after Unity 2021.3.4f1
