### ISSUE TITLE
Unity Serial Not Being Properly Extracted From Personal License

### ISSUE THREAD

**Issue by AndrewKahr** [game-ci/unity-builder#393]
**Bug description**

Recent changes to how build parameters is setup for Cloud Builds causes the action to skip the license parsing step and assume a serial is provided. This causes a hang and failed builds.

**How to reproduce**

Make a github actions build for a windows or mac build host (ie IL2CPP builds)

**Expected behavior**

Build should succeed with no license issues.

**Additional details**

The issue is here: https://github.com/game-ci/unity-builder/blob/8abce48a488351f8b4d3118ca7e4baaf22fc2041/src/model/build-parameters.ts#L79

Printing out the booleans, `Cli.options === undefined` evaluates to false while the other 2 conditions evaluate to true. This needs to be refactored to always run for GitHub Actions builds if a serial isn't provided.

**Comment by webbertakken** [comment]
Nice find! People have been reporting this bug on Discord quite a few times as well but we didn't find the cause.

**Comment by frostebite** [comment]
could you try a build targeting the release branch "cloud-runner-develop" to confirm the fix

**Comment by AndrewKahr** [comment]
@frostebite Gave it a test build and it's looking good. Thanks for the fix!
