### ISSUE TITLE
Add git safe.directory

### ISSUE THREAD

**Issue by achimmihca** [game-ci/unity-builder#399]
**Context**

I use git commands in custom Unity build actions. For example, I read the current commit hash to have a unique version in the compiled executable: `git rev-parse --short --verify HEAD`

Problem is that git now has an issue because of a recent security update (see https://stackoverflow.com/questions/71901632/fatal-unsafe-repository-home-repon-is-owned-by-someone-else ):
```
Error building Player: BuildFailedException: Command: git rev-parse --short --verify HEAD Failed
fatal: unsafe repository ('/github/workspace' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
```

**Suggested solution**

I tried the suggestion and added `git config --global --add safe.directory /github/workspace` as a shell command that is run before the Unity builder. I tried it with and without `sudo`.
However, this does not seem to work.

Please add an option to add such a `safe.directory` as part of the unity build runner.

As alternative, where in the build do I have to run the git command? Where to configure it in the YAML file?

You can find
- the build output [here](https://github.com/UltraStar-Deluxe/Play/runs/6355358706)
- the yaml config [here](https://github.com/UltraStar-Deluxe/Play/blob/master/.github/workflows/build-main-game.yml)
- the custom Unity build script [here](https://github.com/UltraStar-Deluxe/Play/blob/master/UltraStar%20Play/Packages/playshared/Editor/BuildInfoGenerator.cs) respectively [here](https://github.com/UltraStar-Deluxe/Play/blob/master/UltraStar%20Play/Packages/playshared/Editor/GitUtils.cs)

Thanks for the help!

**Comment by webbertakken** [comment]
The reason why it doesn't work is that you're changing the global git config on the runner, but not inside the docker image that contains the Unity Editor.

This would be an oddly specific setting to be passing into builder tbh. We'll think about whether we want to put that in our public API. I'm also curious what comes out of git after this release as it affected quite a few people after updating git.

In the meantime you can just delete the `.git` folder of either the parent or the child project, which will solve your problem immediately.

**Comment by achimmihca** [comment]
If I remove the `.git` folder then git commands will not work anymore? If I do this, how should git know which commit hash to return?

> you're changing the global git config on the runner, but not inside the docker image that contains the Unity Editor.

I tried to run the git config command from within the Unity build in the same way how I run the other Git command.
This failed but without proper error message in the log. Dont know why.

For now, I just ignore the missing git commit hash in the build.
Please, let me know if you have news about the feature in git.

**Comment by webbertakken** [comment]
> If I remove the .git folder then git commands will not work anymore? If I do this, how should git know which commit hash to return?

The security issue only happens if you have a nested repository. So one repository is inside another one, and the parent repository has a different owner.

- Are you able to identify which repository lives inside which other repository? 
- And if yes, have you tried deleting the .git folder of the parent repository?

I'm assuming the latter will in fact not affect running git commands, as you propose in your rhetorical questions, because if you were running these git commands in the parent repository you wouldn't have stumbled upon the security issue. 

- In case my assumption is wrong, would you mind giving some extra details that helps us understand the nested repository situation in your workflow? 
- And specifically why removing the parent .git folder wouldn't work in this case?

**Comment by achimmihca** [comment]
Thanks, I think I misunderstood the error message from Git.
Will try some stuff.

Anyway, this issue does not seem to be related at all to unity-builder. It is probably a bug on my side.
Sorry for the inconvenience. Thanks again for the help.

**Comment by webbertakken** [comment]
You're very welcome.

Feel free to open an issue at any time should you still have trouble getting it to work.
