### ISSUE TITLE
ownership of output

### ISSUE THREAD

**Issue by gucio321** [game-ci/unity-builder#415]
**Bug description**

build result has root ownership

**How to reproduce**

- run builder
- `ls -l`
- you will see that owner is root (should be worker?)

**Expected behavior**

I suppose that owner should be worker nor root

**Additional details**

I need to use `sudo mv` to rename my directory

**Comment by webbertakken** [comment]
This doesn't happen on GitHub hosted workers.

On self-hosted workers the username could be `runner` or `worker` or other, so you'll have to specify which one it using the [chownFilesTo](https://game.ci/docs/github/builder#chownfilesto) parameter.

Closing this but do feel free to add another comment if your problem persists.

**Comment by gucio321** [comment]
> This doesn't happen on GitHub hosted workers.

Strange I've noticed it on GitHub hosted runner...

**Comment by AndrewKahr** [comment]
Same here actually, maybe github changed the name of the runner? I didn't notice the parameter was available and just manually ran chown in a step after builder.

**Comment by webbertakken** [comment]
Ah good to know it also happens on GitHub hosted runners.

We'll consider setting that parameter by default.
