### ISSUE TITLE
Environment variable to disable git repo checks

### ISSUE THREAD

**Issue by SelfhostedPro** [game-ci/unity-builder#417]
**Context**

I'm using a submodule to use one of my unity projects inside of a flutter app and have both built at the same time in the same repo. I'm running into the following error when building the unity side of things even though all of the files required to build the project are there:

```
Failed to run "git rev-list --count 1ae98cf9e5d20e8bd637b9efe21d2e25c4de0424".
 In-command error caught: Error: The process '/usr/bin/git' failed with exit code 128
 ```
 
**Suggested solution**

Add an environment variable that disables checking the git repo in the job.

**Considered alternatives**

Forking the project and adding this myself for my own use.

**Additional details**

https://discord.com/channels/710946343828455455/710946344264794219/991749950780223598

**Comment by ErcinDedeoglu** [comment]
I have same problem and this blocks to move forward with game-ci. Now investigating another solution... :/
