### ISSUE TITLE
Cannot configure Docker to use more than 1GB of memory when running a Windows build on Windows

### ISSUE THREAD

**Issue by wilg** [game-ci/unity-builder#432]
Absolutely losing my mind trying to figure out why Docker on Windows has a 1GB memory limit that won't allow my app to build. This seems to be the issue: https://stackoverflow.com/questions/43460770/docker-windows-container-memory-limit but none of the workarounds seem to work properly. I think passing a `-m` flag or whatever into the usage of Docker from unity-builder might work, but I have no idea. Any help is greatly appreciated. Using a local action runner on Windows 11 Pro.

**Comment by wilg** [comment]
I forked it to allow me to just pass memory and cpu count vars, since I could not figure out how to change the defaults. https://github.com/wilg/unity-builder

**Comment by AndrewKahr** [comment]
Try updating to v4 and see if this is solved now. It should automatically pick a higher limit now but you can manually override the value too.
