### ISSUE TITLE
Docker Build Path Problem

### ISSUE THREAD

**Issue by emrahyumuk** [game-ci/unity-builder#433]
**Bug description**

Game CI Unity build runs in /github/workspace path in docker. After getting build on Ubuntu, I move the file to macos with artifact. But some build inputs search files in /github/workspace path. For example sdk classes files (/github/workspace/iOS/Classes/Blabla.swift) I can't create /github path in github hosted macos runner. And It does not find file in  path. 

**How to reproduce**

If I can pass the path in docker as a parameter, it will work without any problems. But default is /github/workspace. I don't know if there is a way to do this

**Comment by AndrewKahr** [comment]
@emrahyumuk I've added a `dockerWorkspacePath` parameter to my test branch. If you provide it with the path that you want it to mount to within the docker container, ie: `/my/path/to/folder`, it should fix the issue you've been facing. Could you test that parameter using the action `AndrewKahr/unity-builder@misc-fixes` and let me know if that works?

**Comment by AndrewKahr** [comment]
@emrahyumuk Apologies, I don't think the commit got pushed. If you tested it before now, it might've been outdated.

**Comment by AndrewKahr** [comment]
@emrahyumuk Were you able to test the changes and did they fix the issue?
