### ISSUE TITLE
Build logs (from inside Docker container) do not get saved

### ISSUE THREAD

**Issue by wilg** [game-ci/unity-builder#438]
When the build fails (and doesn't exit! https://github.com/game-ci/unity-builder/issues/325) you have no way to see the actual Unity build log anymore.

It seems to be temporarily visible while docker is running, but does not persist so you can't download it from GitHub actions to review why it failed.

**Comment by AndrewKahr** [comment]
Does the build log not stream to the GitHub actions console and get persisted by that even if a workflow is canceled?

**Comment by davidmfinol** [comment]
I'm wondering if this is still an issue?
