### ISSUE TITLE
Configuration option to suppress `-quit`

### ISSUE THREAD

**Issue by DecentM** [game-ci/unity-builder#442]
**Context**

I'm trying to use unity-builder to run a pre-existing build pipeline, that uses callbacks heavily internally. Because the initial step is also a callback based function, synchronously the function finishes execution while build preparations are still happening. Since the function I specified ends while there are still things happening, it causes Unity to quit because the `-quit` parameter is hardcoded into the build script. I believe I could still use unity-builder as-is if there was a way to suppress `-quit` and it'd let me just call `EditorApplication.Exit` when I know that the build process finished.

**Suggested solution**

Please add a new [configuration option](https://game.ci/docs/github/builder#configuration-options) to the GitHub Action that causes the `-quit` command line argument to not be passed to the editor.

**Considered alternatives**

If I understand correctly, Unity should treat returned coroutines as an indicator of the build's status, but in practice the editor quit before the build could start regardless when I tried. I also tried running a Task and having the main thread wait for in synchronously but as expected, that just hung the editor.

**Additional details**

Starting from [this line](https://github.com/game-ci/unity-builder/blob/3d0eb0805bbe2df90e319abbe42e41d0b9105625/dist/platforms/ubuntu/steps/build.sh#L128) in the build script, every other argument is customisable, except for `-quit`. Was it intended to be controllable at some point perhaps?

**Comment by webbertakken** [comment]
Hey @DecentM, thanks for creating this issue and especially for your detailed description.

This is planned and can be tracked in https://github.com/game-ci/cli/issues/13 (the CLI will hold the core logic for unity-builder in v3.0.0).

**Comment by DecentM** [comment]
Thanks for the quick response @webbertakken, that's great to know!  

Is there a way to use it right now instead of having to halt my progress on the feature I wanted to use this config option for? I can see that the issue is still open, so maybe it'd be worth it to backport it into v2 as it feels like a gap in the current functionality that doesn't depend on other changes you guys are planning for v3.

**Comment by webbertakken** [comment]
Certainly. 

You can fork unity-builder and change entrypoint.sh and its sub-scripts inside the dist folder to do so.
