### ISSUE TITLE
Building using Game-CI causes more required features for android than manual build

### ISSUE THREAD

**Issue by eivinf** [game-ci/unity-builder#458]
**Bug description**

Building using Game-CI causes "com.google.ar.core.depth" to be required event when set to optional in project settings.  Manual build causes no such issue. This in turn significantly reduces the number of compatible devices.

![image](https://user-images.githubusercontent.com/40213867/193600933-50244a89-e23d-4fde-bb48-3b184c985301.png)

**How to reproduce**
1.  Create a new unity project and install AR-foundation and AR-core
2.  In project settings -> XR-plugin management set plug-in provider for android to AR-core
3.  In project settings -> XR-plugin management--> ARCore set depth to "Optional"
4.  Build manually and you will find the requirement of feature "com.google.ar.core.depth" to be false in androidManifest.xml. Building using Game-CI causes the same feature to be true in androidManifest.xml. 
![image](https://user-images.githubusercontent.com/40213867/193603941-906f030e-3e91-443b-9726-3ea09e95e74a.png)
![image](https://user-images.githubusercontent.com/40213867/193603969-e329e3d5-dfa2-4532-a626-81c7a78c4832.png)

**Expected behavior**

Building using Game-CI should not set "com.google.ar.core.depth" to required when set as optional in project settings. 

**Additional details**
This is the code used for building:
![image](https://user-images.githubusercontent.com/40213867/193607442-3e062921-9268-4584-8b59-403dc58fa1da.png)

**Comment by webbertakken** [comment]
> Building using Game-CI causes "com.google.ar.core.depth" to be required event when set to optional in project settings. Manual build causes no such issue.

This is most likely not caused by GameCI specifically, but just by running the build from command line. GameCI is just a tool that makes it easy for you to run a build from command-line. It's probably wise to report this to the plugin maker or set the correct setting in your build script (that are otherwise set automatically when building from the GUI).

**Comment by eivinf** [comment]
Hm interesting, however the changes in the GUI relates to changes in the file "/Assets/XR/Settings/AR Core Settings.asset" which as you can see in the build script I print out to make sure it is correct. Could this still be an issue with building from the terminal even though this file is correct, as the setting then exist in a file even without an active GUI of unity open?

**Comment by webbertakken** [comment]
Yea definitely. It wouldn't be the first time. It could be that some required library isn't present and (silently?) doesn't let us know, and we've seen command-line behaving different than the UI in quite a few other cases as well.

One example is the compression for WebGL builds.
