### ISSUE TITLE
Use node16 for GitHub Actions, instead of deprecated node12

### ISSUE THREAD

**Issue by ChristianTellefsen** [game-ci/unity-builder#464]
**Context**

GitHub Actions log warnings about using deprecated node 12. This is the message:

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: game-ci/unity-builder

**Suggested solution**

Update the actions to use node 16.

**Additional details**

![Screenshot 2022-10-12 093945](https://user-images.githubusercontent.com/1049621/195282917-f3177733-8a39-4b16-9df6-cb1d18a1c405.png)

**Comment by davidmfinol** [comment]
Fixed by https://github.com/game-ci/unity-builder/pull/465
