### ISSUE TITLE
Using 'unityLicensingServer' in game-ci/unity-builder@v2 reports a warning and error, refusing to build

### ISSUE THREAD

**Issue by ChristianTellefsen** [game-ci/unity-builder#480]
**Bug description**

[Your docs](https://game.ci/docs/github/builder#license-server) say that you now support 'unityLicensingServer' as a parameter to unity-builder.

We tried to use this parameter for doing an enterprise build, instead of building using a professional license w/ serial+username+password. The parameter is reported as not supported, with a warning message saying `Unexpected input(s) 'unityLicensingServer'`. Then we get an error message saying `Missing Unity License File and no Serial was found`.

**How to reproduce**

Use the `unityLicensingServer` parameter with game-ci/unity-builder@v2

**Expected behavior**

I expect to be using the Unity license server.

**Additional details**

Our code, which seems to match your example in the docs:

```
      # Build the project using GameCI (https://game.ci/docs/github/builder)
      - name: Build Unity project
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityLicensingServer: https://our-licensing.server-name.com:8080
          versioning: None
```

Warnings and errors in the log:

```
Warning: Unexpected input(s) 'unityLicensingServer', valid inputs are ['targetPlatform', 'unityVersion', 'customImage', 'projectPath', 'buildName', 'buildsPath', 'buildMethod', 'customParameters', 'versioning', 'version', 'androidVersionCode', 'androidAppBundle', 'androidKeystoreName', 'androidKeystoreBase64', 'androidKeystorePass', 'androidKeyaliasName', 'androidKeyaliasPass', 'androidTargetSdkVersion', 'sshAgent', 'gitPrivateToken', 'chownFilesTo', 'allowDirtyBuild', 'postBuildSteps', 'preBuildSteps', 'customJobHooks', 'customJob', 'awsBaseStackName', 'cloudRunnerCluster', 'cloudRunnerCpu', 'cloudRunnerMemory', 'cachePushOverrideCommand', 'cachePullOverrideCommand', 'readInputFromOverrideList', 'readInputOverrideCommand', 'kubeConfig', 'kubeVolume', 'kubeStorageClass', 'kubeVolumeSize', 'cacheKey', 'checkDependencyHealthOverride', 'startDependenciesOverride']
 [...]   
Error: Missing Unity License File and no Serial was found. If this
                          is a personal license, make sure to follow the activation
                          steps and set the UNITY_LICENSE GitHub secret or enter a Unity
                          serial number inside the UNITY_SERIAL GitHub secret.
```

**Comment by webbertakken** [comment]
The warning is just because nobody added the input parameter to the `action.yml` file in the root.

The error should be accurate. I don't believe this is a bug.

**Comment by ChristianTellefsen** [comment]
Hi, thanks for the quick reply!

I looked at the code, and it does seem to me like the way to use this feature to add the unityLicensingServer parameter.
I did add:

`unityLicensingServer: "https://unity-license.***.com:8080"`

But it seems to be failing here, which I guess it should not, since I did set that input?

```
    if (Input.unityLicensingServer === '') {
      if (!process.env.UNITY_SERIAL && Input.githubInputEnabled) {
        // No serial was present, so it is a personal license that we need to convert
        if (!process.env.UNITY_LICENSE) {
          throw new Error(`Missing Unity License File and no Serial was found. If this
                          is a personal license, make sure to follow the activation
                          steps and set the UNITY_LICENSE GitHub secret or enter a Unity
                          serial number inside the UNITY_SERIAL GitHub secret.`);
```

**Comment by webbertakken** [comment]
It's a bit difficult to debug this locally until we finish our CLI ([roadmap](https://github.com/orgs/game-ci/projects/4/views/1)). Maybe you can see the logs in the licensing server or add a proxy to see what the request looks like (if it's connecting to the server at all).
