### ISSUE TITLE
When setting versioning to 'None', the build version is still overridden

### ISSUE THREAD

**Issue by Jon-ScaryBeasties** [game-ci/unity-builder#483]
**Bug description**

When setting the versioning of a build to None, the build version in Unity is set to "None" and the build is then failed. 

**How to reproduce**

Set the versioning system to None

**Expected behavior**

It's expected that the version is left alone and the version number that was already in place in the build is used

**Additional details**

I believe this is a simple case sensitive error. When the version is set, it checks for "none" and returns, however, the action forces the user to use None, which does not match and allows the version number to be set as "None" instead.

**Comment by AndrewKahr** [comment]
I just tested this and it doesn't appear to be an issue. The action asks the user to specify `None` but internally that gets translated to `none` so it appears to respect the versioning strategy. Are you still seeing this issue?

**Comment by AndrewKahr** [comment]
Closing as this doesn't appear to be an issue. Feel free to reopen if it pops up again.
