### ISSUE TITLE
Generated build is empty

### ISSUE THREAD

**Issue by juniobiel** [game-ci/unity-builder#486]
Hello Guys.
I'm configuring the actions at my repository. I made a cube and upload to test the actions. So, when I download the artifact generated at GitHub Actions, this is empty.
Has something that can I doing wrong?

This is the action with artifacts
https://github.com/juniobiel/2d-game-project/actions/runs/3751849670

**Comment by webbertakken** [comment]
Welcome @juniobiel,

Could you try to list the current working directory after the build to see if the `/build/` folder indeed exists. And if it does list the contents of it. Make sure the target path is exactly the same as what you're using to upload the artifact.

Generally if no 0 bytes are uploaded, it means the path is somehow incorrect.

**Comment by juniobiel** [comment]
Hi webber.

I found the problem. The builder action uses /build to determine the path of build output. I'm thinking that this path was necessary on my repo, but it isn't.

I just changed the path param to `build` and it works.

**Comment by webbertakken** [comment]
Great! Happy that worked for you.
