### ISSUE TITLE
Keystore for android is not created under Windows.

### ISSUE THREAD

**Issue by rasentry** [game-ci/unity-builder#490]
**Bug description**

The content of ANDROID_KEYSTORE_BASE64 is completely ignored.
For Ubuntu there is a part of code responsible for this https://github.com/game-ci/unity-builder/blob/d066039c2625695bf07b68a681aafe0c1bb28a9f/dist/platforms/ubuntu/steps/build.sh#L69

But for Windows there is nothing like that. So I get message "Keystore not found"

**Comment by davidmfinol** [comment]
Should be fixed by https://github.com/game-ci/unity-builder/pull/478


It has not yet been added to `unity-builder@v2`, but you should be able to use `unity-builder@main` in the meantime.

**Comment by davidmfinol** [comment]
v3 has been released, so this should be done now.
