### ISSUE TITLE
Support For Semantic Versions Include Release types (i.e. alpha, beta, etc.)

### ISSUE THREAD

**Issue by BlankDev117** [game-ci/unity-builder#491]
**Bug description**

Semantic versioning does not appear to catch builds with tags that include a pre-release type

**How to reproduce**

1. Create a tag with semantic version including a pre-release tag type (alpha, beta, etc.). Notice the "found semantic version" is incorrect. In this case, the semantic version is `0.0.1-alpha`
![image](https://user-images.githubusercontent.com/7662822/212459283-7b9e5bc3-aabf-4c04-8d15-1c34c36148ab.png)

2. Create a tag with semantic version not including a pre-release tag type. Notice the "found semantic version" is correct. In this case, the semantic version is `0.0.1`
![image](https://user-images.githubusercontent.com/7662822/212459332-c85550c1-1c02-48a7-a8fe-caeeca04df07.png)

**Expected behavior**

Using semantic versions that include pre-release types should work and be passed onto unity as normal, i.e. a tag similar to `0.0.1-alpha` or `0.0.1-beta` should pass onto unity without error.

**Comment by AndrewKahr** [comment]
@BlankDev117 I think if you use tag versioning instead of semver, it should pass it through properly. Semver seems to be used to generate a semver style version where you tag `major.minor` and it uses the number of commits since the tag as the `patch` version number.

**Comment by AndrewKahr** [comment]
Closing this as it is working as expected.
