### ISSUE TITLE
IL2CPP not installed in windows-2021.3.13f1-windows-il2cpp-1 image

### ISSUE THREAD

**Issue by Cherden** [game-ci/unity-builder#500]
Hi.
I have a problem building using the [`unityci/editor:windows-2021.3.13f1-windows-il2cpp-1`](https://hub.docker.com/layers/unityci/editor/windows-2021.3.13f1-windows-il2cpp-1/images/sha256-76de7569642d65fa41ce1e90ca312ca083075892c76d0c936746ef93a548cdff?context=explore) image. When calling `BuildPipeline.BuildPlayer` I get the error `Error building Player: Currently selected scripting backend (IL2CPP) is not installed.`.
The build target is set the following way: `EditorUserBuildSettings.SwitchActiveBuildTarget(NamedBuildTarget.Server, BuildTarget.StandaloneWindows64)`.
My logs confirm that the scripting backend is actually set and `BuildPlayer` is called with the parameters:
```
:: Performing build
	Scenes:Assets/Scenes/Server/Server.unity, Assets/Scenes/Shared/Shared.unity, 
	Path: C:\workspace\Builds\StandaloneWindows64\Server.exe
	Target: StandaloneWindows64
	Options: None
```
While figuring out whether the problem is on my side I executed the build script on my host machine, where it works. As a sanity check I also tried building for target `StandaloneWindows64` as a non-server build using the image, which results in the same error.

Thanks in advance.

**Comment by davidmfinol** [comment]
Can you share a minimal reproducible example?
I use I2CPP and have working StandaloneWindows64 builds with `unityci/editor:windows-2021.3.16f1-windows-il2cpp-1`: https://github.com/finol-digital/Card-Game-Simulator/actions/runs/4088041461/jobs/7050146747

**Comment by davidmfinol** [comment]
There's been a lot of changes to the Windows docker images recently.
Is this still an issue?
