### ISSUE TITLE
Action doesn't change files permission on docker fail

### ISSUE THREAD

**Issue by MrFastwind** [game-ci/unity-builder#504]
**Bug description**

if unity fails with fatal signal, and docker fails, the directory remain with root permissions, and it doesn't change it back nor set it to *chownFilesTo*  variable.

**How to reproduce**
It's difficult, in my case was a an error with PlayerSettings.asset.
Others:
- set *chownFilesTo*
- run without being root
- have docker permissions

**Expected behavior**

even if it fails, the directory permission should change to *chownFilesTo* if present.
so it's possible to delete it without root permissions.

**Additional details**
log
```bash
Scripts have compiler errors.

Aborting batchmode due to failure:
Scripts have compiler errors.

./External/baselib/builds/Include/Internal/../C/Internal/Baselib_Semaphore_FutexBased.inl.h(151): Assertion failed (count >= 0) - Destruction is not allowed when there are still threads waiting on the semaphore.
Caught fatal signal - signo:5 code:128 errno:0 addr:(nil)
Trace/breakpoint trap (core dumped)
Exit code was: 133
Error: The process '/usr/bin/docker' failed with exit code 133
```

also it seams that docker code 133 means that it catched a SIGTRAP (i suppose from unity)

**Comment by miguelvieirart** [comment]
Had problems with that, but managed to fix using a step that runs on failure to run chown on current directory

- name: Chown files on failure
        if: failure()
        run: |
          chown -R user:group ./

**Comment by MrFastwind** [comment]
> Had problems with that, but managed to fix using a step that runs on failure to run chown on current directory
> 
> - name: Chown files on failure
>         if: failure()
>         run: |
>           chown -R user:group ./
> 

Thank you, but it would only work if the runner had root permission or sudo, and i don't have it in my environment

I would like to avoid spining up a container (that have root permission) and change owner from it.

Why unity is so peeky on permission?

Well, i'll probably going to close the issue my self in the next days

**Comment by AndrewKahr** [comment]
v4 now has a `runAsHostUser` parameter to have the docker container not run as root which should fix these permission issues. If you run on a self hosted runner, just set it to true.
