### ISSUE TITLE
v2.2.0 breaks builds on Linux machines

### ISSUE THREAD

**Issue by muojp** [game-ci/unity-builder#508]
Hello. It seems that v2.2.0 release broke Android/iOS builds on Linux machines.

**Bug description**

Run a CI in an ordinal manner.

GitHub Actions log says:
```
Run game-ci/unity-builder@v2
  with:
    versioning: None
    customImage: custom-editor:2021.3.11f1-ios-1.0.1
    projectPath: Unity/develop
    buildMethod: OurOwnBuildMethod
    customParameters: -stage Test
    targetPlatform: iOS
    unityVersion: auto
    androidAppBundle: false
    androidSymbolType: none
    sshAgent: public
    awsBaseStackName: game-ci
    cloudRunnerCluster: local
    kubeVolumeSize: 5Gi
    watchToEnd: true
    cacheUnityInstallationOnMac: false

/home/ubuntu/bin/docker run --workdir /github/workspace --rm --env UNITY_LICENSE --env UNITY_SERIAL=SERIAL_NUMBER --env UNITY_VERSION=2021.3.11f1 --env PROJECT_PATH=Unity/develop --env BUILD_TARGET=Android --env BUILD_NAME=Android --env BUILD_PATH=build/Android --env BUILD_FILE=Android.apk --env BUILD_METHOD=OurOwnBuildMethod --env VERSION=none --env ANDROID_VERSION_CODE=0 --env ANDROID_EXPORT_TYPE=androidPackage --env ANDROID_SYMBOL_TYPE=none --env CUSTOM_PARAMETERS=-stage Test --env GITHUB_REF=some/ref --env GITHUB_SHA=d5c7c793f9aa98253d76da0d51bcf4f1108cc67d --env GITHUB_REPOSITORY=ourrepo --env GITHUB_ACTOR=Somebody --env GITHUB_WORKFLOW=Build TEST/DEV/BOYOD App --env GITHUB_EVENT_NAME=workflow_dispatch --env GITHUB_ACTION=__self --env GITHUB_EVENT_PATH=/home/ubuntu/actions-runner/_work/_temp/_github_workflow/event.json --env RUNNER_OS=Linux --env RUNNER_TOOL_CACHE=/home/ubuntu/actions-runner/_work/_tool --env RUNNER_TEMP=/home/ubuntu/actions-runner/_work/_temp --env RUNNER_WORKSPACE=/home/ubuntu/actions-runner/_work/ourrepo --env SSH_AUTH_SOCK=/ssh-agent --env UNITY_SERIAL --env GITHUB_WORKSPACE=/github/workspace --env SSH_AUTH_SOCK=/ssh-agent --volume /home/ubuntu/actions-runner/_work/_temp/_github_home:/root:z --volume /home/ubuntu/actions-runner/_work/_temp/_github_workflow:/github/workflow:z --volume /home/ubuntu/actions-runner/_work/ourrepo/ourrepo:/github/workspace:z --volume /home/ubuntu/actions-runner/_work/_actions/game-ci/unity-builder/v2/dist/default-build-script:/UnityBuilderAction:z --volume /home/ubuntu/actions-runner/_work/_actions/game-ci/unity-builder/v2/dist/platforms/ubuntu/steps:/steps:z --volume /home/ubuntu/actions-runner/_work/_actions/game-ci/unity-builder/v2/dist/platforms/ubuntu/entrypoint.sh:/entrypoint.sh:z --volume /home/ubuntu/actions-runner/_work/_actions/game-ci/unity-builder/v2/dist/unity-config:/usr/share/unity3d/config/:z --volume public:/ssh-agent --volume /home/runner/.ssh/known_hosts:/root/.ssh/known_hosts:ro custom-editor:2021.3.11f1-android-1.0.1 /bin/bash -c /entrypoint.sh
docker: Error response from daemon: error while creating mount source path '/home/runner/.ssh/known_hosts': mkdir /home/runner: permission denied.
Error: The process '/home/ubuntu/bin/docker' failed with exit code 126
Run game-ci/unity-builder@v2
```

**How to reproduce**

 - Launch an EC2/Ubuntu instance and setup a rootless Docker in it
 - Register the instance as a GItHub Actions self-hosted runner and trigger an Android / iOS build inside Linux instance

**Expected behavior**

Builds fine.

**Additional details**

This is because sshAgent has a default value since v2.2.0:
https://github.com/game-ci/unity-builder/commit/0efa1855a3c37ab64c3a9e221a939a967932923c#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6R89

This might be avoided by explicitly setting `sshAgent: ''` in your `with` params (not confirmed).

**Comment by davidmfinol** [comment]
Thanks for reporting! Rolling back `v2`  to `v2.1.2` and marking `v2.2.0` as a pre-release for now.

**Comment by muojp** [comment]
Thank you!

**Comment by AndrewKahr** [comment]
Odd, I didn't intentionally change that. I'll dig into when/why that got changed but it can probably just be reverted.

**Comment by AndrewKahr** [comment]
Whoops I see what happened, meant to update the symbol type and put it under ssh. Will make a PR to fix it.

**Comment by davidmfinol** [comment]
We've merged the fix for this to main and would like to promote it to `v2.2.1`.
@muojp Could you check if `game-ci/unity-builder@main` works for you?

**Comment by muojp** [comment]
@davidmfinol thank you for treating this issue! Sure, I will give v2.2.1 a try!

**Comment by muojp** [comment]
@davidmfinol 
Hello. We are experiencing a bit weird situation while testing `@main`.
Build procedure starts fine, but we get an error when the build comes to a final stage.

Note: Our build (for iOS) runs perfectly w/ `@v2 (= v2.1.2)` so I'm thinking we might need to check the difference deeply. Also, I hesitate to paste full log here because it's too large and does contain much secret information.

**Comment by AndrewKahr** [comment]
@muojp Can you provide the specific error that is being thrown?

**Comment by muojp** [comment]
@AndrewKahr 
That's the difficult part.

Final output is below but it's far from informative log so we need to inspect more.

```
2023-02-23T00:38:54.0208691Z Build succeeded
2023-02-23T00:38:54.4103445Z 
2023-02-23T00:38:54.4104099Z ###########################
2023-02-23T00:38:54.4105044Z #       Build output      #
2023-02-23T00:38:54.4105942Z ###########################
2023-02-23T00:38:54.4106438Z 
2023-02-23T00:38:54.4479479Z total 8.0K
2023-02-23T00:38:54.4480827Z drwxr-xr-x 2 root root 4.0K Feb 23 00:27 .
2023-02-23T00:38:54.4481993Z drwxr-xr-x 3 root root 4.0K Feb 23 00:27 ..
2023-02-23T00:38:54.4483154Z Changing to "/github/workspace/_activate-license~" directory.
2023-02-23T00:38:54.4484348Z /github/workspace/_activate-license~ /github/workspace
2023-02-23T00:38:54.4485317Z /github/workspace
2023-02-23T00:39:08.7114014Z ##[error]There was an error building the project. Please read the logs for details.
```

**Comment by AndrewKahr** [comment]
@muojp Recommend opening the raw log and searching for `Error` or `Exception`.

**Comment by muojp** [comment]
Yes... I searched for 'error / fail's and found out we have plenty of error classes and harmless errors in our codebase.

**Comment by AndrewKahr** [comment]
There's usually a section that says

`
Warnings: X
Errors: X
`

Were there any errors reported there?

**Comment by davidmfinol** [comment]
@muojp Any update?

**Comment by muojp** [comment]
@davidmfinol 
Hello. Not getting much progress yet. I will dig into this again tomorrow.

**Comment by muojp** [comment]
Anyway, it's a separate issue from the original one I reported. I assume it could be nice to file another issue for the build error and close this (#508) for now.

**Comment by davidmfinol** [comment]
Sure, would be good to have a new issue.
