### ISSUE TITLE
Unity Builder Serial Activation Limit Hit

### ISSUE THREAD

**Issue by AndrewKahr** [game-ci/unity-builder#516]
**Bug description**

It seems a non-free license is being used to activate Unity in the tests which is causing the activation limit to be hit due to the number of parallel runs.

**How to reproduce**

- Run Linux, mac, and windows builds simultaneously.

**Expected behavior**

No activation errors.

**Additional details**

Can the repo switch to a free license so these limits aren't hit? Otherwise will need a way to ensure the parallel run count is kept lower.

CC: @davidmfinol @GabLeRoux

**Comment by davidmfinol** [comment]
We'll create a new free account and use that. Planning to use `maintainers@game.ci` as the email address and just waiting on some setup for it.

**Comment by webbertakken** [comment]
[Worker](https://github.com/webbertakken/email-worker) for forwarding email into our maintainers discord channel is completed.

Unfortunately I'm struggling to get it deployed due to a [bug](https://discord.com/channels/595317990191398933/1079085311465902160) in Cloudflare.

In the meantime I've forwarded emails to me and I'll paste them into the email channel manually until that's resolved.

**Comment by davidmfinol** [comment]
I've set `UNITY_EMAIL=maintainers@game.ci`, along with the corresponding `UNITY_PASSWORD` for the free Unity account.
I've also updated the `UNITY_LICENSE`.
However, I'm not sure how to set the `UNITY_SERIAL`.
I can only find the Serial key at https://id.unity.com/en/subscriptions if I pay for a PLUS or PRO license, but we see this issue if we use a paid account.
After looking through our discord logs, I'm pretty sure I had set `UNITY_SERIAL` before, but I'm still not sure about how did we have this working before?

**Comment by AndrewKahr** [comment]
If you look in the ulf, unbase64 developer data

**Comment by webbertakken** [comment]
Re: [Worker](https://github.com/webbertakken/email-worker). This is now also completed.

**Comment by davidmfinol** [comment]
Thanks @AndrewKahr , I've now updated `UNITY_SERIAL`  as well, so now we just need to test and confirm that it's all set correctly now.

**Comment by AndrewKahr** [comment]
I've got #511 ready for merging 😀

**Comment by davidmfinol** [comment]
This should be fixed now, right? 
I see some windows and mac builds still failed, but that's unrelated right?

**Comment by AndrewKahr** [comment]
Yeah the failed runs are just hangs so this is done.
