### ISSUE TITLE
Mininum Android SDK version not met

### ISSUE THREAD

**Issue by James-Silvester** [game-ci/unity-builder#518]
**Bug description**

Unable to deploy onto the google play store as it seems that the image does not have a latest enough version of the android sdk:

``` Google Api Error: Invalid request - Your app currently targets API level 30 and must target at least API level 31.```

**How to reproduce**

Try to do a deploy onto the google play store following the steps here - https://game.ci/docs/github/deployment/android

**Expected behavior**

It has an up-to-date android sdk and the deployment works successfully

**Additional details**

**Comment by James-Silvester** [comment]
Googles API requirements: https://developer.android.com/google/play/requirements/target-sdk

**Comment by James-Silvester** [comment]
Oh,, having a poke around and it looks like the build is still on 2021 - https://github.com/game-ci/docker/blob/2e768f462c1fcdf3fd4bd17c2b5b8156c40664bf/images/ubuntu/editor/Dockerfile.

This seems quite out of date now

**Comment by James-Silvester** [comment]
Ahhh hang on I do see that later images are published. Although I have just found that you can specify the unity image

https://game.ci/docs/github/builder#unityversion

That was not obvious in the other steps and also the default version seems quite old. Running a test run and possibly need to do a doc change to make it more obvious/change the default image to a newer one

**Comment by webbertakken** [comment]
The default version is auto-detected from the Unity version defined in your project.

The problem is actually that Unity Editor ships with outdated SDKs. Our images ship the officially supported SDKs that Unity Hub installs by default, for each editor version. 

You might indeed need a custom image or use one from someone else in the community who went through the same steps already.

**Comment by davidmfinol** [comment]
We added `androidTargetSdkVersion` for this. 
```
with:
    androidTargetSdkVersion: AndroidApiLevel31
```
Let us know if it works for you: https://game.ci/docs/github/builder#androidtargetsdkversion

**Comment by davidmfinol** [comment]
I've also raised a PR to help new users in the future: https://github.com/game-ci/documentation/pull/367

**Comment by James-Silvester** [comment]
@davidmfinol yes I have given that a go and it works perfectly! Also a good addition to the docs.

Overall they are very good docs - managed to set up a pipeline in a day and now have deploys right to google play which is awesome! I see that there is that other issue and happy for this one to be closed
