### ISSUE TITLE
Failing Unity CI Build with 2021.3

### ISSUE THREAD

**Issue by Div-Inworld** [game-ci/unity-builder#519]
**Bug description**

My unity project can be built locally just fine but fails constantly through the git actions unity-builder@v2

**How to reproduce**

Setup Unity Project with sample scene in Editor Build Settings. Add Assets, Packages and ProjectSettings Folder to repo.

**Expected behavior**

Expect Git Action to build without a problem in the Actions tab but it fails

**Additional details**

Has been reported twice in the past already with sparse useful information.  Appears to be potentially related to incremental builds and .dag json file from it. 
The .dag file mentioned in this comment isn't loaded but subsequently created and written to. This same line shows on my successful unity clean build locally so I do not think this is the issue

https://github.com/game-ci/unity-builder/issues/360#issuecomment-1077465299

https://github.com/game-ci/docker/issues/196

https://github.com/game-ci/unity-builder/issues/360

**Comment by davidmfinol** [comment]
Can you search your logs for `error` to see what the error is?

**Comment by davidmfinol** [comment]
Closing due to lack of info.
Feel free to re-open if error message is available.
