### ISSUE TITLE
some files and directories are owned by root:root and github runner user is not able to delete them :: self-hosted runner

### ISSUE THREAD

**Issue by davi020** [game-ci/unity-builder#521]
# Build the Unity WebGL build using game-ci/unity-builder@v2
      - name: Build WebGL
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          buildName: WebGLBuild
          buildsPath: builds/webgl
          chownFilesTo: username:group (Tried with githib runner userid and group id as well)
          
      even I tried to use the chownFilesTo: username:group in my workflow file, still some files and directories are created with root:root permissions. 
      
      Directory names - builds,Library,Logs

Any help to fix this?

**Comment by AndrewKahr** [comment]
Is it just he build the output folder or other folders too?

**Comment by davi020** [comment]
@AndrewKahr  - These are the files that are owned by root in self-hosted runner after this action - 

[root@xxxxxxx]# ll | grep root
drwxr-xr-x.  2 root      root       6 Mar  7 09:26 _activate-license~
drwxr-xr-x.  3 root      root      19 Mar  7 09:26 builds
drwxr-xr-x.  9 root      root    4096 Mar  7 09:27 Library
drwxr-xr-x.  2 root      root       6 Mar  7 09:26 Logs
drwxr-xr-x.  2 root      root   12288 Mar  7 09:28 Temp
[root@xxxxxxxxx]#

**Comment by AndrewKahr** [comment]
@davi020 It's interesting that _activate-license~ is there as the build scripts delete that folder after the build. Is this after a successful build or after a failed build?

**Comment by davi020** [comment]
@AndrewKahr - Due to root:root permissions none of our workflows are not yet successful. The _activate-license~ is not getting deleted right after the build phase as well.

**Comment by davi020** [comment]
@AndrewKahr  - Question - Why chownFilesTo is not working as expected here?

**Comment by AndrewKahr** [comment]
That's what I'm trying to work out as we have code for that already:
```
# Make a given user owner of all artifacts
if [[ -n "$CHOWN_FILES_TO" ]]; then
  chown -R "$CHOWN_FILES_TO" "$BUILD_PATH_FULL"
  chown -R "$CHOWN_FILES_TO" "$UNITY_PROJECT_PATH"
fi
```

**Comment by AndrewKahr** [comment]
@davi020 I added a debug print to the chown part. Can you test the build using `AndrewKahr/unity-builder@misc-fixes` and see if it prints out `Changing ownership of files to <chownFilesTo>`

**Comment by davi020** [comment]
@AndrewKahr  - Sure, Thanks!

**Comment by AndrewKahr** [comment]
v4 now has a `runAsHostUser` parameter to have the docker container not run as root which should fix these permission issues. If you run on a self-hosted runner, just set it to true.
