### ISSUE TITLE
Mac build not Intel

### ISSUE THREAD

**Issue by AbabiyaAbajo** [game-ci/unity-builder#523]
New to GameCI and CI/CD in general. I've managed to make Window and Mac build but Mac is strange.

Build target is StandaloneOSX. According to the documentation, it should build MacOS on intel architecture: 
https://docs.unity3d.com/ScriptReference/BuildTarget.StandaloneOSX.html

But my runner keeps giving me an error:
Error building Player: Apple silicon support requires Metal enabled in Graphic APIs for Mac.

When making the build manually, I can over come this by changing the architecture for Mac to Intel.

I can also overcome this issue by turning on Metal but this causes problem on Silicon chips within my app.

My question: How come BuildTarget/StandaloneOSX not actually intel? How can I make it intel and not Apply Silicon + Intel?

Thanks in advance!

**Comment by a-mirecki** [comment]
+1 any update on this?

**Comment by davidmfinol** [comment]
You would need to use a custom build method for this (docs: https://game.ci/docs/github/builder/#buildmethod). 

In your custom build method, you would need to add:
```
#if UNITY_EDITOR && UNITY_STANDALONE_OSX
UnityEditor.OSXStandalone.UserBuildSettings.architecture = UnityEditor.OSXStandalone.MacOSArchitecture.x64;
#endif
```

**Comment by a-mirecki** [comment]
Thank you, this worked well. Simpler approach is using build preprocess with this code, also works like a charm https://docs.unity3d.com/ScriptReference/Build.IPreprocessBuildWithReport.OnPreprocessBuild.html
