### ISSUE TITLE
Build fails in action despite working on local machine and worker log says "Build succeeded"

### ISSUE THREAD

**Issue by Podden** [game-ci/unity-builder#535]
**Bug description**

My WebGL Build works on my local windows machine but fails on ubuntu-latest action. The log says "Build succeeded" and seems to work fine but the last output is "[error]There was an error building the project. Please read the logs for details."
The logs says after the Unity build is succeeded that my mono runtime and class libraries are out of sync but I don't know what that means. Maybe this produces the error in the end?

**Expected behavior**

Build works on Github Actions worker

**Additional details**
This is a webGL project with local addressables on Unity 2022.2.15

[logfile.txt](https://github.com/game-ci/unity-builder/files/11443304/logfile.txt)

**Comment by ngoisaoquay** [comment]
I got the same error, any solution for this?

**Comment by ShiroKatake** [comment]
same for me too. This is happening with 2022.3.4f1. Windows and Mac are building just fine. I don't know how it happened. Granted this was previously 2021.x, and it was recently upgraded, but I took heed of the warning and cleared the cache and redid the verifications

**Comment by Sonorpearl** [comment]
Could this also be this issue?
https://github.com/game-ci/unity-builder/issues/563

**Comment by AndrewKahr** [comment]
Try updating to v4, there were changes to build result checks
