### ISSUE TITLE
There was a problem communicating with the license server

### ISSUE THREAD

**Issue by ErcinDedeoglu** [game-ci/unity-builder#536]
Hello,
A problem started after sometime. There was nothing changed on CI/CD pipeline.
I'm getting: There was a problem communicating with the license server

Logs:
> 12:53:34 Step 5/15: WebGL - EXEC (LICENSE) (Command Line)
> 12:53:34   Starting: /opt/buildagent/temp/agentTmp/custom_script15947779215146769774
> 12:53:34   in directory: /opt/buildagent/work/a0cf9f7531cf2be
> 12:53:34   Unity Editor version:    2020.3.43f1 (75bff06b76bf)
> 12:53:34   Branch:                  2020.3/staging
> 12:53:34   Build type:              Release
> 12:53:34   Batch mode:              YES
> 12:53:34   System name:             Linux
> 12:53:34   Distro version:          #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023
> 12:53:34   Kernel version:          5.4.0-148-generic
> 12:53:34   Architecture:            x86_64
> 12:53:34   Available memory:        32112 MB
> 12:53:34   [LicensingClient] Channel doesn't exist: "LicenseClient-root"
> 12:53:34   [Licensing::Module] Successfully launched the LicensingClient (PId: 48)
> 12:53:35   [SignatureVerifier] Application signature verification not supported on this platform.
> 12:53:35   [Licensing::Module] Successfully connected to LicensingClient on channel: "LicenseClient-root" (connect: 0.61s, validation: 0.07s, handshake: 0.00s)
> 12:53:35   [Licensing::Module] Connected to LicensingClient (PId: 48, launch time: 0.00, total connection time: 0.68s)
> 12:53:35   Entitlement-based licensing initiated
> 12:53:35   [LicensingClient] Licenses updated successfully
> 12:53:36   [UnityConnectServicesConfig] config is NOT valid, switching to default
> 12:53:39   User **@**.com logged in successfully
> 12:53:40   
> 12:53:40   LICENSE SYSTEM [2023512 12:53:40] Starting license activation with account **@**.com
> 12:53:40   
> 12:53:40   
> 12:53:40   LICENSE SYSTEM [2023512 12:53:40] Opening https://license.unity3d.com/update/poll?cmd=9&tx_id=***&(serial removed)
> 12:53:40   
> 12:53:40   LICENSE SYSTEM [2023512 12:53:40] Posting <?xml version="1.0" encoding="UTF-8"?><root><SystemInfo><IsoCode>C.UTF</IsoCode><UserName>(unset)</UserName><OperatingSystem>Linux 5.4 Ubuntu 18.04 64bit</OperatingSystem><OperatingSystemNumeric>504</OperatingSystemNumeric><ProcessorType>Intel(R) Xeon(R) Platinum 8280L CPU @ 2.60GHz</ProcessorType><ProcessorSpeed>2593</ProcessorSpeed><ProcessorCount>8</ProcessorCount><ProcessorCores>8</ProcessorCores><PhysicalMemoryMB>32112</PhysicalMemoryMB><ComputerName>***</ComputerName><ComputerModel>PC</ComputerModel><UnityVersion>2020.3.43f1</UnityVersion><SupportedLicenseVersion>6.x</SupportedLicenseVersion></SystemInfo><License id="Terms"><MachineID Value="***=" /><MachineBindings><Binding Key="1" Value="***" /><Binding Key="2" Value="***" /></MachineBindings><UnityVersion Value="2020.3.43f1" /></License></root>
> 12:53:40   
> 12:54:01   
> 12:54:01   LICENSE SYSTEM [2023512 12:54:1] Headers:
> 12:54:01   
> 12:54:01   
> 12:54:01   LICENSE SYSTEM [2023512 12:54:1] Error fetching https://license.unity3d.com/update/poll?cmd=9&tx_id=***&(serial removed)
> 12:54:01   Cancelling DisplayDialog: Information There was a problem communicating with the license server. Would you like to do a manual activation instead?
> 12:54:01   This should not be called in batch mode.
> 12:54:01   Process exited with code 1
> 12:54:01   Process exited with code 1 (Step: WebGL - EXEC (LICENSE) (Command Line))
> 12:54:01   Step WebGL - EXEC (LICENSE) (Command Line) failed

**Comment by ErcinDedeoglu** [comment]
I know this problem is not really related to GameCI but could you give me a clue please?

**Comment by ErcinDedeoglu** [comment]
Incredible... Unity started forcing using TLS1.3, which was not supported by the host machine. apt-get update and upgrade solved the problem.

**Comment by juliencharrel** [comment]
@ErcinDedeoglu How did you manage to do it inside a GitHub runner? I'm stuck with the same error
