### ISSUE TITLE
Github actions hosted runner fails for WSAPlayer with `windows-2022`

### ISSUE THREAD

**Issue by camnewnham** [game-ci/unity-builder#542]
**Bug description**

Building WSAPlayer using github actions  with a hosted runner fetches an incompatible docker image and produces the error: `The container operating system does not match the host operating system.`

This happens with `windows-2022`. `windows-2019` works as expected.

**How to reproduce**

- Create a github actions workflow with `runs-on: windows-latest`
- Attempt to build a `WSAPlayer` project

**Expected behavior**

Unity project is built.

**Additional details**

Github hosted runner details:
```
Current runner version: '2.305.0'
Operating System
  Microsoft Windows Server 2022
  10.0.20348
  Datacenter
Runner Image
  Image: windows-2022
  Version: 20230612.1
  Included Software: https://github.com/actions/runner-images/blob/win22/20230612.1/images/win/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20230612.1
```

Error in build step:
```
Status: Downloaded newer image for unityci/editor:windows-2022.3.1f1-universal-windows-platform-1
docker: Error response from daemon: hcs::CreateComputeSystem 57f9bea707270d54c11b52dc1b4a88087228987678ecf821e16279ce12abacc3: The container operating system does not match the host operating system.
Error: The process 'C:\Windows\system32\docker.exe' failed with exit code 125
```

**Comment by davidmfinol** [comment]
This issue is dependent on updating the docker images: https://github.com/game-ci/docker/issues/213

**Comment by AndrewKahr** [comment]
V4 is now released and uses windows-2022
