### ISSUE TITLE
`-customParameters` is not used on Windows builds (github actions)

### ISSUE THREAD

**Issue by camnewnham** [game-ci/unity-builder#543]
**Bug description**

As per title. Flags from `-customParameters` don't get included in in the launch arguments.

**How to reproduce**

This is visible in the test runs on this repo (github actions). 

The [workflow file](https://github.com/game-ci/unity-builder/actions/runs/4708968116/workflow#L79) includes `customParameters: -profile SomeProfile -someBoolean -someValue exampleValue` 

However the logs from the Build step show that these are not included for windows:
```
COMMAND LINE ARGUMENTS:
C:\Program Files\Unity\Hub\Editor\2022.2.6f1\Editor\Unity.exe
-batchmode
-quit
-nographics
-username
***
-password
(hidden)
-serial
(hidden)
-projectPath
c:/BlankProject
-logfile
Successfully changed project path to: c:/BlankProject
C:/blankproject
```
**Expected behavior**

`-customParameters` are included in the command line arguments for Unity as per other platforms

**Additional details**

This can be observed from the logs [here](https://github.com/game-ci/unity-builder/actions/runs/4708968116/jobs/8353192179) and reproduced by running a windows build using `game-ci/unity-builder@v2` on a `windows-2019` github actions runner

**Comment by AndrewKahr** [comment]
Have you tried v4? Custom parameters should be working there
