### ISSUE TITLE
Branch is dirty, maniefst.json

### ISSUE THREAD

**Issue by MadScientist11** [game-ci/unity-builder#554]
I'm completely new to CI/CD stuff and I spent a day trying to set up a build with game-ci. 
I'm trying to build using the example from docs.
![image](https://github.com/game-ci/unity-builder/assets/63862082/7818c538-1967-4b54-9fa5-41f42fbf9250)
And here is what I'm getting
![image](https://github.com/game-ci/unity-builder/assets/63862082/1d902419-1032-4337-815f-4915f4161e51)
I tried resolving this by adding all those packages to my project, but then I got out of space error, which is ridiculous since it was an empty project. How can I fix this? I ran out of ideas.

**Comment by davidmfinol** [comment]
For out of space issue, you can try a couple of options: https://game.ci/docs/troubleshooting/common-issues#no-space-left-on-device

**Comment by stariluz** [comment]
It seems to me that the problem is instead related to this: https://game.ci/docs/troubleshooting/common-issues/#branch-is-dirty.
@MadScientist11, were you able to solve it? I'm encountering the same error, but in my case, I'm only adding the manifest.json file from the Packages folder.

**Comment by stariluz** [comment]
I solved it.
@davidmfinol. I don’t know how you knew the issue, but yes, you were right. First, I had to separate the jobs to run them in parallel, which triggered the "out of space" issue. So, I used the action you recommended in the docs to free up space, and all my builds started passing. Thank you so much!

As a side note, my project is currently very small (with an almost empty scene, some scripts, and the usual Unity packages), and it seems strange to me that using the parallel workflow and the free-up-space action is considered optional in the docs. I can’t imagine a project that could run without this configuration (at least in Unity 6, which I’m using).

**Comment by sbeginner** [comment]
Just for the issue mentioned in the title 'Branch is dirty, manifest.json'. 
In my case, I figured out the package 'com.unity.toolchain.linux-x86_64' was added after using 'unity-test-runner@v4'. 

To solve it manually, I cat the modified file for more details, then installed the missing package.
```
      - name: Cat Info
        run: |
          cat Packages/manifest.json
```
