### ISSUE TITLE
Build failed without any error

### ISSUE THREAD

**Issue by JayMehta97** [game-ci/unity-builder#555]
**Bug description**
I am trying to generate a GitHub action build for the first time and it failed after running for an hour without any error. 

Earlier it was failing because `no space left on device issue` then I fixed it using the below block:
```
 name: Free Disk Space for Android
        run: |
          df -h
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker images -q)
          df -h
```

Then it started failing with error `The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.` so I changed my `ubuntu-latest` to `ubuntu-20.04` as it worked for other people.

Running the unity-builder after these changes fails without any error. I just started using unity-builder yesterday and till now haven't been able to generate a build successfully. I have attached my build script and the action logs file to this report. 

**Expected behavior**
Generate build

**Additional details**

[Build and Deployment.txt](https://github.com/game-ci/unity-builder/files/12288534/Build.and.Deployment.txt)
[github-action-logs.txt](https://github.com/game-ci/unity-builder/files/12288535/github-action-logs.txt)

**Comment by MetcalfeTom** [comment]
We are also experiencing the same problem - we would love a solution

It happens for Android builds only.  Building for iOS and WebGL works perfectly

**Comment by MetcalfeTom** [comment]
@JayMehta97 after deleting the action/workflow cache on Github, and updating to `jlumbroso/free-disk-space@v1.3.1` we were able to build again
