### ISSUE TITLE
Disabling the check for the "Build results" output?

### ISSUE THREAD

**Issue by mikeage** [game-ci/unity-builder#563]
**Context**

We use a custom build action, and it doesn't print the same format of "Build results" that the default build method does. As a result, we're told that our build fails, even when it actually succeeds.

**Suggested solution**

Add an option to disable this check.

**Considered alternatives**

Adding this game-ci specific print to our build method.

**Additional details**

Raised on discord at https://discord.com/channels/710946343828455455/1143838569220280321

**Comment by AndrewKahr** [comment]
Try updating to v4 and see if this is solved now

**Comment by mikeage** [comment]
Unfortunately, v4 broke our flow for building from forks (where we had a license baked in to the github file, since secrets are inaccessible), and I'm not sure if the proper fix is to put a username/password there too. I've asked on the Discord (https://discord.com/channels/710946343828455455/1174438356755697784/1174438356755697784) and once this is resolved, I'll be able to see if our PR at https://github.com/icosa-foundation/open-brush/pull/557 works.

**Comment by mikeage** [comment]
Indeed, this works now. Thanks
