### ISSUE TITLE
iOS fail to copy bundle resources

### ISSUE THREAD

**Issue by buger404** [game-ci/unity-builder#583]
**Bug description**

When the builder entered the 'copy bundle resources' phase, it encountered an error, stating, 'No such file or directory.'

However, I have verified that the relative bundle exists in the Unity-generated project. Is there an issue with the setup, or could this be a bug?

My assumption is that not all the files from my project directory were copied to the location where the build was executed. Alternatively, they might have been moved, but the Xcode project settings, such as file paths, have remained unchanged.

**How to reproduce**

- Build the Xcode project requiring the copy bundle resources.

**Expected behavior**

Successfully built the app.

**Additional details**

The directory structure of my Xcode project that Unity generated:
* ./AntiAdictionResources
* ./Classes
* ./Data
* ./Frameworks
* ./Libraries
* ./MainApp
* ./TapCommonResource
* ./UnityData.xcassets
* ./UnityFramework
* ./Unity-iPhone
* ./Unity-iPhone Tests
* ./Unity-iPhone.xcodeproj
* Info.plist
* LaunchScreen-iPad.png
* LaunchScreen-iPad.storyboard
* LaunchScreen-iPhone.storyboard
* LaunchScreen-iPhoneLandscape.png
* LaunchScreen-iPhonePortrait.png
* process_symbols.sh

Error logs:
```
▸ Touching UnityFramework.framework (in target 'UnityFramework' from project 'Unity-iPhone')
▸ Copying /Users/runner/Library/Developer/Xcode/DerivedData/Unity-iPhone-evovqqetpacjyecjqgexzmnihqel/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/InstallationBuildProductsLocation/Applications/AntiAddictionTest.app/TapCommonResource.bundle

❌  error: /github/workspace/build/iOS/iOS/TapCommonResource/TapCommonResource.bundle: No such file or directory (in target 'Unity-iPhone' from project 'Unity-iPhone')


▸ Copying /Users/runner/Library/Developer/Xcode/DerivedData/Unity-iPhone-evovqqetpacjyecjqgexzmnihqel/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/InstallationBuildProductsLocation/Applications/AntiAddictionTest.app/Data
▸ Copying /Users/runner/Library/Developer/Xcode/DerivedData/Unity-iPhone-evovqqetpacjyecjqgexzmnihqel/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/InstallationBuildProductsLocation/Applications/AntiAddictionTest.app/AntiAdictionResources.bundle

❌  error: /github/workspace/build/iOS/iOS/AntiAdictionResources/AntiAdictionResources.bundle: No such file or directory (in target 'Unity-iPhone' from project 'Unity-iPhone')


** ARCHIVE FAILED **


The following build commands failed:
	CpResource /Users/runner/Library/Developer/Xcode/DerivedData/Unity-iPhone-evovqqetpacjyecjqgexzmnihqel/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/InstallationBuildProductsLocation/Applications/AntiAddictionTest.app/TapCommonResource.bundle /github/workspace/build/iOS/iOS/TapCommonResource/TapCommonResource.bundle (in target 'Unity-iPhone' from project 'Unity-iPhone')
	CpResource /Users/runner/Library/Developer/Xcode/DerivedData/Unity-iPhone-evovqqetpacjyecjqgexzmnihqel/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/InstallationBuildProductsLocation/Applications/AntiAddictionTest.app/AntiAdictionResources.bundle /github/workspace/build/iOS/iOS/AntiAdictionResources/AntiAdictionResources.bundle (in target 'Unity-iPhone' from project 'Unity-iPhone')
(2 failures)
[14:42:50]: Exit status: 65
```

**Comment by buger404** [comment]
If necessary, you can add the following package to an empty Unity project by editing the file `Packages/manifest.json`:
```
"com.leancloud.storage": "https://github.com/leancloud/csharp-sdk-upm.git#storage-1.0.2",
"com.taptap.tds.common":"https://github.com/TapTap/TapCommon-Unity.git#3.19.0"
```
Afterwards, attempt to build this for iOS without any Unity scripts.

**Comment by buger404** [comment]
This can be accomplished on a local Mac OS, so I believe the package is not the source of the problem.

**Comment by GabLeRoux** [comment]
Certainly!

---

If I understand well, we should be able to reproduce this issue by following these steps:

1. Create a blank Unity project
2. Make sure a scene is added to the build settings.
3. Edit the `Packages/manifest.json` file to include the specified packages:

```json
{
  "dependencies": {
    "com.leancloud.storage": "https://github.com/leancloud/csharp-sdk-upm.git#storage-1.0.2",
    "com.taptap.tds.common":"https://github.com/TapTap/TapCommon-Unity.git#3.19.0"
  }
}
```
4. Attempt to build this for iOS locally, there shouldn't be any problem
5. Configure Github Actions with GameCI to build for iOS and observe if the 'copy bundle resources' phase errors occur as described.

Let me know if you think there's something else to this. It might be useful to create a public repository where this can be reproduced.

Did this happen on a specific Unity version?

**Comment by buger404** [comment]
Yes, that's correct. And it appears to be unrelated to the version of Unity. 
I have created a public repository to reproduce this issue: [buger404/repo-for-unity-ci-issue](https://github.com/buger404/repo-for-unity-ci-issue)
Thank you for your prompt help!

**Comment by buger404** [comment]
I've tackled this issue by adding the following step:
```
      - name: Fix Absolute Paths
        env:
          IOS_BUILD_PATH: ${{ format('{0}/build/iOS', github.workspace) }}
        run: |
          awk '{gsub("/github/workspace/build/iOS/iOS/", "")}1' "$IOS_BUILD_PATH/iOS/Unity-iPhone.xcodeproj/project.pbxproj" > modified_project.pbxproj
          mv modified_project.pbxproj "$IOS_BUILD_PATH/iOS/Unity-iPhone.xcodeproj/project.pbxproj"
          cat "$IOS_BUILD_PATH/iOS/Unity-iPhone.xcodeproj/project.pbxproj"
```
The issue here is that Unity generates an Xcode project with file references using absolute paths, but it seems that Fastlane moves the Xcode project to a different location, which causes problems during the copying process. 
I'm not entirely sure whether this should be fixed by unity-builder or Fastlane.
