### ISSUE TITLE
Build Stuck

### ISSUE THREAD

**Issue by firdiar-mita** [game-ci/unity-builder#592]
**Bug Build Stuck**
Just my assumption, if the license is expired, the build stuck

**How to reproduce**
use expired license, and run android build
![image](https://github.com/game-ci/unity-builder/assets/147171097/7a0ed07a-d6de-48a6-96a6-acd11f53a9cb)

**Expected behavior**
Build Fail due to expired license

**Comment by webbertakken** [comment]
Could you show timestamps for that log? I suspect it might run for the maximum amount of time, meaning the worker is stuck.

Also be sure to copy paste the relevant part and put it in a `<details>` field, so that it is searchable for other users with the same issue.

**Comment by AndrewKahr** [comment]
Closing as activation had an overhaul in v4 which fixed most activation issues
