### ISSUE TITLE
"unityci/editor:ubuntu-2022.3.13f1-windows-mono-2" image not hosted on dockerhub

### ISSUE THREAD

**Issue by nobnak** [game-ci/unity-builder#594]
**Bug description**

> Run game-ci/unity-builder@v3.0.0
> ...
> Unable to find image 'unityci/editor:ubuntu-2022.3.13f1-windows-mono-2' locally
> docker: Error response from daemon: manifest for unityci/editor:ubuntu-2022.3.13f1-windows-mono-2 not found: manifest unknown: manifest unknown.
> See 'docker run --help'.
> Error: The process '/usr/bin/docker' failed with exit code 125

**How to reproduce**

Building a Unity 2022.3.13f1 project with uses: game-ci/unity-builder@v3.0.0

**Expected behavior**

There is [unityci/editor:ubuntu-2022.3.12f1-windows-mono-2](https://hub.docker.com/layers/unityci/editor/ubuntu-2022.3.12f1-windows-mono-2/images/sha256-00163ab9a073970d8a4694de8cef8a3eed7f0e916a05055fe2568dcf2d5772e3?context=explore) image for Unity 2022.3.12f1.
But for Unity 2022.3.13f1,I can only find out [unityci/editor:ubuntu-2022.3.13f1-windows-mono-3](https://hub.docker.com/layers/unityci/editor/ubuntu-2022.3.13f1-windows-mono-3/images/sha256-4e6e3b084ecc2eb6c6bfce41809423b3ed24050bd5443da0f212c9d09259d010?context=explore) image.

The builder should use "mono-3" image instead of "mono-2".

**Comment by AndrewKahr** [comment]
We're in the process of releasing Unity-Builderv4 which will switch to v3 images. Until then, the absolute latest editor versions won't be available on v2.

**Comment by Javernaut** [comment]
@AndrewKahr , will the Unity-Builderv4 have some sort of a imageVersion parameter to specify v2 or v1 for images? Just to be able to pick older images for ancient projects. And at the same time be forward compatible with even newer versions of images than v3.

**Comment by AndrewKahr** [comment]
You can force a specific image with the customImage parameter and even build your own images and use them that way, but we don't have a parameter for major version. The new image version for the most part is backwards compatible and we haven't cut any editor versions so v4 should be able to build old projects too.

**Comment by AndrewKahr** [comment]
Try updating to v4 and see if this is solved now

Also added parameters to allow rolling back image versions and more flexibility with a custom registry.
