### ISSUE TITLE
Preserve license folder on Mac, if it already exists

### ISSUE THREAD

**Issue by erik-qde** [game-ci/unity-builder#595]
**Context**

The Unity Licensing Client is storing it's license information in `/Library/Application Support/Unity`. This directory is usually not writable by ordinary users so it has to be created manually or with elevated permissions.
The `entrypoint.sh` script for the GitHub runner is using `sudo` to create and also to remove the entire directory after it has returned the license. This causes license errors for other Unity operations that are not based on game-ci which expects the directory to be setup correctly from the beginning.

**Suggested solution**

I think the current behavior should be preserved if the directory **does not exist** when `entrypoint.sh` starts.
If the **directory exist** at the start, the permissions **should not** be set to `777` and the directory shouldn't be removed after the license is returned.

Something like this is what I'm suggesting:
```
REMOVE_DIR=0
if [ ! -e "Library/Application\ Support/Unity" ]; then
   REMOVE_DIR=1
   sudo mkdir /Library/Application\ Support/Unity
   sudo chmod -R 777 /Library/Application\ Support/Unity
fi

...

if [ $REMOVE_DIR -eq 1 ]; then
   sudo rm -r /Library/Application\ Support/Unity
fi
```

**Considered alternatives**

* Force Unity Technologies to store license information in an optional location, say `~/Library/Application Support/Unity`... Good luck with that.
* Create the directory with `sudo` in all other build scripts would of course work, but that would make this "hack" propagate throughout the entire build pipeline.
* Just removing all files in the folder instead of the folder itself would work as well but could break some intricate pre-existing setup for some users.

**Additional details**

https://github.com/game-ci/unity-builder/blob/main/dist/platforms/mac/entrypoint.sh

**Comment by AndrewKahr** [comment]
V4 should now do this. It will only create it if it doesn't already exist and will not delete it.
