### ISSUE TITLE
Retry on license failures

### ISSUE THREAD

**Issue by asbjornu** [game-ci/unity-builder#597]
**Context**
Something like 10-20% of our builds fail due to not being able to obtain a license from Unity. These failures seem to be intermittent and a re-run of the build usually "fixes" the problem. 

**Suggested solution**
It would be nice if the `game-ci/unity-builder` action was able to detect a license failure and retry N times before failing the entire build.

**Considered alternatives**
We could use something like [action::retry](https://github.com/marketplace/actions/retry-action) to retry the `game-ci/unity-builder` action on failure, but that would not take into consideration why the action failed, and would retry build failures that are due to faults of our own (and need us to change stuff in order to succeed, making the retry unnecessary).

**Additional details**
The build log for the last license failure looks like this (identifiers abbreviated with `…` due to privacy; no idea whether this is needed or not, but better to fail on the safe side, imho):

```log
[Licensing::Module] Trying to connect to existing licensing client channel...
[Licensing::IpcConnector] Connection attempt to the License Client on channel: "LicenseClient-root" failed because channel doesn't exist; code: "0x80000002"
[Licensing::Module] Successfully launched the LicensingClient (PId: 150)
[Licensing::IpcConnector] Successfully connected to the License Client on channel: "LicenseClient-root"
[SignatureVerifier] Application signature verification not supported on this platform.
[Licensing::Client] Handshaking with LicensingClient:
  Version:                 1.12.1+9338cad
  Session Id:              3ebc…8b34
  Correlation Id:          6ede…aecf
  External correlation Id: 4320…8029
  Machine Id:              D7nT…YdM=
[Licensing::Module] Successfully connected to LicensingClient on channel: "LicenseClient-root" (connect: 0.62s, validation: 0.12s, handshake: 0.00s)
[Licensing::IpcConnector] Successfully connected to the License Notification on channel: "LicenseClient-root-notifications"
[Licensing::Module] Connected to LicensingClient (PId: 150, launch time: 0.00, total connection time: 0.74s)
[Licensing::Module] Error: Access token is unavailable; failed to update
[Licensing::Module] Error: Failed to return entitlement license
[Licensing::Client] Successfully queried for the EntitlementGroupsDetails
[Licensing::Module] Error: Serial number unavailable for ULF return; aborting operation
```

**Comment by eronnen** [comment]
wouldn't it be better to perform the retry inside the docker?

**Comment by mikeage** [comment]
Especially since there doesn't seem to be a guaranteed way to detect license failure as opposed to a real issue, I'd also like to see a bit more robustness built in.

**Comment by asbjornu** [comment]
I have a theory that license activation fails due to concurrent (parallel) builds trying to activate the same license key simultaneously. I'm now testing to see whether [configuring `concurrency`](https://docs.github.com/en/actions/using-jobs/using-concurrency) might help. I'll report my findings here once done.

**Comment by mikeage** [comment]
Any idea what that limit might be? We do 10 builds in parallel, and sometimes they all run, sometimes one or two fail; occasionally more. But because our setup, and different steps that run prior to the build, we know that generally no more than 3 or 4 start building at the same time, although they all overlap during the build (in other words, they might not be doing license activation at the same time, but they have a license activated at the same time).

If it turns out that there's a limit on the number of concurrent activation actions, it'd be very useful if we can separate the activation step from the full build; if we have to limit our parallel builds to a few, we're still better off with retries, as statistically, it'll complete faster.

**Comment by AndrewKahr** [comment]
The latest update to v4 has retry activation logic and should be a lot more consistent in activating licenses

**Comment by mikeage** [comment]
This looks promising, but it seems like activation is actually far less reliable now for us, and the retries don't actually help (they run, but it still fails in exactly the same way each time). 

https://discord.com/channels/710946343828455455/1178007708809580705
