### ISSUE TITLE
How to build for il2cpp

### ISSUE THREAD

**Issue by edqx** [game-ci/unity-builder#610]
I feel like this should be a trivial question for unity-builder, but I'm struggling to build my game with il2cpp.

First I got this:
![image](https://user-images.githubusercontent.com/60631511/206699901-a16e27f2-d1ba-4228-94a1-ec506f849e21.png)

Then I tried to use a docker image that ended in `-il2cpp`, one of the ones here: https://hub.docker.com/r/unityci/editor/tags?page=1&name=windows-il2cpp

That got an issue to do with not being able to be ran on linux architecture:
![image](https://user-images.githubusercontent.com/60631511/206700230-9c574cf4-80ad-4818-9d29-e49c617fc878.png)

... So I moved to use Windows Server for my GitHub actions, where now I get this:
![image](https://user-images.githubusercontent.com/60631511/206700367-9e23c0d3-8f8b-4102-8105-0a9de425f83b.png)

But I think this is a lost cause, since `UNITY_EMAIL`, `UNITY_PASSWORD` and `UNITY_LICENSE` are all set fine in the repository's secrets tab.

I think I'm completely on the wrong track here and missing something really obvious, like a bit of xy problem going on.

Thanks.

**Comment by AndrewKahr** [comment]
@asbjornu Note if you want to leverage Burst, you will need to build Android using Windows (now windows-2022 as we updated the images) and build iOS using macos (any version works, generally macos-latest works well). Closing this as the issue appears to be solved.
