### ISSUE TITLE
Unable to find image 'unityci/editor:ubuntu-2022.3.16f1-android-2' locally

### ISSUE THREAD

**Issue by Heurazio** [game-ci/unity-builder#616]
Reproduce: Run game-ci/unity-builder@v3.0.0 and a unity version 2022.3.16f1

```
Unable to find image 'unityci/editor:ubuntu-2022.3.16f1-android-2' locally
docker: Error response from daemon: manifest for unityci/editor:ubuntu-2022.3.16f1-android-2 not found: manifest unknown: manifest unknown.
```

How to reproduce

Building a Unity 2022.3.16f1 project with uses: game-ci/unity-builder@v3.0.0

Expected behavior

There is an image for Unity 2022.3.16f1.
The builder should use "mono-3" image instead of "mono-2".

**Comment by GabLeRoux** [comment]
I recommend updating to v4
game-ci/unity-builder@v4

**Comment by Heurazio** [comment]
When running this step `- uses: game-ci/unity-builder@v4`

I get this error:

`Unable to find image 'unityci/editor:ubuntu-2022.3.16f1-android-3' locally
docker: Error response from daemon: manifest for unityci/editor:ubuntu-2022.3.16f1-android-3 not found: manifest unknown: manifest unknown.`

BTW: Thanks for the hint - was not aware of v4

**Comment by GabLeRoux** [comment]
ok nevermind, oversight on my end, update of v4 was necessary, but the unity version just released. have a look at this page:
https://game.ci/docs/docker/versions

Use `unityci/editor:ubuntu-2022.3.15f1-android-3.0.0` instead. When the version will be availalbe on unity's website, our bot will publish the docker image in the following hour.

**Comment by Heurazio** [comment]
That actually solved the build problem. Thanks a lot
