### ISSUE TITLE
dedicated server builds just started to fail

### ISSUE THREAD

**Issue by js-9** [game-ci/unity-builder#631]
**Bug description**
Linux dedicated server builds just started to fail with the following:
```
Refreshing native plugins compatible for Editor in 6.87 ms, found 3 plugins.
Preloading 1 native plugins for Editor in 0.08 ms.
Asset Pipeline Refresh (id=2ce0e46c50f0887869176fe3265106d1): Total: 0.093 seconds - Initiated by StopAssetImportingV2(NoUpdateAssetOptions)
Error building Player: Dedicated Server support for Linux is not installed.
Unloading 62 Unused Serialized files (Serialized files now loaded: 0)
Unloading 4032 unused Assets / (1.2 MB). Loaded Objects now: 8626.
Memory consumption went from 230.4 MB to 229.2 MB.
Total: 14.270858 ms (FindLiveObjects: 0.995997 ms CreateObjectMapping: 0.322662 ms MarkObjects: 9.289027 ms  DeleteObjects: 3.662310 ms)

Build Finished, Result: Failure.
```
Using `customParameters: -standaloneBuildSubtarget Server` the build fails. This just started happening a few minutes ago.

**How to reproduce**

- Try to build a project for linux dedicated server with above custom parameter
- Using unity version 2022.3.8f1
- Builds fails with above error

**Expected behavior**

This was working perfectly until a few minutes ago. Expect build to finish successfully and produce a linux binary.

**Comment by AndrewKahr** [comment]
Hey there, there was a small bug that popped up during a release we just made. A hotfix has already been deployed about a minute ago, can you try re-running your job and see if it's still failing?

**Comment by js-9** [comment]
Yup. Nice job! It's already fixed.
