### ISSUE TITLE
Unity-Builder fails to detect the activation of Unity Pro License (but the License itself gets activated)

### ISSUE THREAD

**Issue by JasperRaccoon** [game-ci/unity-builder#672]
**Bug description**
License activation fails with Unity Pro License, but in the Unity Dashboard the license DID get activated since a seat gets assigned at the moment of the job.

![image](https://github.com/user-attachments/assets/33257885-c266-46c7-809b-3964162809b5)

Here Unity says the license did get activated at the moment of the run of the workflow.
![image](https://github.com/user-attachments/assets/a7c1eda7-416d-45fc-a2a1-acbd441a55bd)

And, a couple instants before the "activation failed" log, it says it succesfully activated the pro license. It's weird 🤣
![image](https://github.com/user-attachments/assets/b7d6a968-b73c-4f30-926b-f3e2d4862e49)

This bug started randomly today without any change to workflows.

**How to reproduce**

Run the unity-builder action with a Unity Pro License

**Expected behavior**

It should recognize the succesful activation of the license and proceed with the build

**Comment by JasperRaccoon** [comment]
It is worth adding that I did verify that the activated license is from the same job, since before running the workflow I removed any previous activation made by unity-builder

**Comment by JasperRaccoon** [comment]
Apparently the error was that, after activating the license it failed to write to "/BlankProject" because it was read only for some reason?
![image](https://github.com/user-attachments/assets/67222409-38cf-4136-b753-c4efc2bb72d5)

I didn't know what to do so I reinstalled my runner from scratch and it works again 🤣 weird, probably something to do with linux permissions or something, idk

**Comment by webbertakken** [comment]
Hey @JasperRaccoon, 

Thank you for reporting the issue and also especially for following up with what worked for you to solve it!
